-- Creating tables for the MHW_DB

-- drop TABLE HUNTER
-- drop TABLE ITEM
-- drop TABLE RANK
-- drop TABLE QUEST
-- drop TABLE EQUIPMENT
-- drop TABLE ARMOR
-- drop TABLE WEAPON
-- drop TABLE ARMOR_SKILL
-- drop TABLE WEAPON_SKILL

-- WEAPON_SKILL has been deleted!

CREATE TABLE QUEST (
  QID int NOT NULL,
  Qname varchar(100) NOT NULL,
  rewards varchar(30) DEFAULT NULL,
  quest_type varchar(16) NOT NULL,
  PRIMARY KEY (QID,Qname),
  CONSTRAINT checkQType CHECK (( quest_type in ( 'Gathering', 'Slaying', 'Capture', 'Expedition', 'Arena', 'Investigation', 'Event', 'Special', 'Delivery', 'Hunting'))) 
);


CREATE TABLE MONSTER (
  M_ID int NOT NULL,
  Mname varchar(20) NOT NULL,
  Msize varchar(5) NOT NULL,
  HZV varchar(30) DEFAULT NULL,
  Mtype varchar(20) NOT NULL,
  threat_level int DEFAULT NULL,
  Q_ID int NOT NULL,
  Q_name varchar(30) NOT NULL,
  PRIMARY KEY (M_ID,Mname),
  FOREIGN KEY (Q_ID, Q_name) REFERENCES QUEST (QID, Qname),
  CONSTRAINT checkSize CHECK ((Msize in ('Small','Large'))),
  CONSTRAINT checkMtype CHECK ((Mtype in ('Small Monster','Fanged Wyvern','Bird Wyvern','Brute Wyvern','Piscine Wyvern','Flying Wyvern','Elder Dragon','Relict','Fanged Beast')))
);

    
CREATE TABLE ARMOR (
  AID int NOT NULL,
  Aname varchar(50) NOT NULL,
  body_part varchar(5) NOT NULL,
  Rarity int NOT NULL,
  Materials varchar(200) DEFAULT NULL,
  PRIMARY KEY (AID,Aname),
  CONSTRAINT checkArarity CHECK (((Rarity > 0) and (Rarity <= 12))),
  CONSTRAINT checkBPart CHECK ((body_part in ('Head','Arm','Body','Waist','Legs')))
);

CREATE TABLE WEAPON (
  WID int NOT NULL,
  Wname varchar(50) NOT NULL,
  Sharpness varchar(6) NOT NULL,
  Affinity int NOT NULL,
  weapon_type varchar(15) NOT NULL,
  Upgrade varchar(1) NOT NULL,
  Element varchar(12) DEFAULT NULL,
  Deco_slots int DEFAULT NULL,
  Materials varchar(200) DEFAULT NULL,
  PRIMARY KEY (WID,Wname),
  CONSTRAINT checkSharpness CHECK ((Sharpness in ('Red','Orange','Yellow','Green','Blue','White','Purple','Ammo'))),--Added Ammo
  CONSTRAINT checkWelement CHECK ((Element in ('Fire','Water','Thunder','Ice','Dragon','Elementless','Paralysis','Sleep','Blast','Poison','Ammo'))),--Added Ammo
  CONSTRAINT checkWType CHECK ((weapon_type in ('Great Sword','Long Sword','Sword & Shield','Dual Blades','Lance','Gunlance','Hammer','Hunting Horn','Switch Axe','Charge Blade','Insect Glaive','Light Bowgun','Heavy Bowgun','Bow'))),--Deleted a duplicated weapon_type- Great Sword
  CONSTRAINT checkWupgrade CHECK ((Upgrade in ('Y','N')))
);

CREATE TABLE HUNTER (
  HID int NOT NULL,
  Hname varchar(30) NOT NULL,
  Palico_name varchar(15) DEFAULT NULL,
  Q_ID int DEFAULT NULL,
  Q_name varchar(30) DEFAULT NULL,
  PRIMARY KEY (HID,Hname),
  FOREIGN KEY (Q_ID, Q_name) REFERENCES QUEST (QID, Qname)
);

CREATE TABLE ITEM (
  IID int NOT NULL,
  Iname varchar(15) NOT NULL,
  Amount int DEFAULT NULL,
  I_type varchar(50) DEFAULT NULL,
  H_ID int DEFAULT NULL,
  H_name varchar(30) DEFAULT NULL,
  PRIMARY KEY (IID,Iname),
  FOREIGN KEY (H_ID, H_name) REFERENCES HUNTER (HID, Hname),
  CONSTRAINT checkNO CHECK (((Amount >= 0) and (Amount <= 99)))
);

CREATE TABLE EQUIPMENT (
  HID int NOT NULL,
  Hname varchar(30) NOT NULL,
  AID int NOT NULL,
  Aname varchar(30) NOT NULL,
  WID int NOT NULL,
  Wname varchar(30) NOT NULL,
  PRIMARY KEY (HID,Hname,AID,Aname,WID,Wname),
  FOREIGN KEY (HID, Hname) REFERENCES HUNTER (HID, Hname),
  FOREIGN KEY (AID, Aname) REFERENCES ARMOR (AID, Aname),
  FOREIGN KEY (WID, Wname) REFERENCES WEAPON (WID, Wname)
);

CREATE TABLE ARMOR_SKILL (
  ASID int NOT NULL,
  ASname varchar(30) NOT NULL,
  ASmax_lvl int NOT NULL,
  ASAvailabilities varchar(200) DEFAULT NULL,
  AID int DEFAULT NULL,
  Aname varchar(30) DEFAULT NULL,
  PRIMARY KEY (ASID,ASname),
  FOREIGN KEY (AID, Aname) REFERENCES ARMOR (AID, Aname),
  CONSTRAINT checkASMLvl CHECK (((ASmax_lvl >= 0) and (ASmax_lvl <= 7)))
);

/* To insert data for armors table:*/
--Good to insert
INSERT INTO ARMOR(AID,Aname,body_part,Rarity, Materials)
VALUES 
(1, 'Leather Headgear','Head',1,'Iron Ore x 2'),
(2, 'Leather Mail','Body',1,'Iron Ore x 1'),
(3, 'Leather Gloves','Arm',1,'Iron Ore x 1'),
(4, 'Leather Belt','Waist',1,'Carbalite Ore x 2 + High-quality Pelt x 1'),
(5, 'Leather Trousers','Legs',1,'Carbalite Ore x 2 + High-Quality Pelt x 1'),
(6, 'Chainmail Headgear','Head',1,'Iron Ore x 2'),
(7, 'Chainmail Vest','Body',1,'Iron Ore x 1'),
(8, 'Chainmail Gloves','Arm',1,'Carbalite Ore x 2 + Dragonite Ore x 2'),
(9, 'Chainmail Belt','Waist',1,'Iron Ore x 1'),
(10, 'Chainmail Trousers','Legs',1,'Carbalite Ore x 2 + Dragonite Ore x 2'),
(11, "Hunter's Headgear",'Head',1,'Jagras Hide x 2 + Jagras Scale x 2'),
(12, "Hunter's Mail",'Body',1,'Jagras Hide x 2 + Monster Bone S x 2'),
(13, "Hunter's Vambraces",'Arm',1,'Jagras Hide + x2 + Jagras Scale + x4'),
(14, "Hunter's Coil",'Waist',1,'Jagras Hide x 1 + Monster Bone S x 1'),
(15, "Hunter's Greaves",'Legs',1,'Jagras Hide x 1 + Monster Bone S x 1'),
(16, 'Bone Helm','Head',1,'Thick Bone x2 + Monster Toughbone x1 + Warped Bone x1'),
(17, 'Bone Mail','Body',1,'Monster Bone S x 1 + Ancient Bone x 1'),
(18, 'Bone Vambraces','Arm',1,'Monster Bone S x 3 + Kestodon Shell x 2'),
(19, 'Bone Coil','Waist',1,'Monster Bone S x 1 + Kestodon Shell x 1'),
(20, 'Bone Greaves','Legs',1,'Monster Bone S x 1 + Ancient Bone x 1'),
(21, 'Vespoid Helm','Arm',1,'Vespoid Shell x 2 + Iron Ore x 2'),
(22, 'Vespoid Mail','Arm',1,'Vespoid Shell x 1 + Machalite Ore x 1'),
(23, 'Vespoid Vambraces','Arm',1,'Vespoid Razorwing x1 + Monster Essence x2 + Thick Bone x2'),
(24, 'Vespoid Coil','Arm',1,'Vespoid Shell x 1 + Iron Ore x 4'),
(25, "Vespoid Greaves",'Legs',1,'Vespoid Wing x 2 + Monster Fluid x 1'),
(26, 'Kestodon Guards', 'Arm', 1, 'Kestodon Husk x3 + Thick Bone x2 + 9000 Gold'),
(27, 'Gajau Boots', 'Legs', 1, 'Gajau Skin x 4 + Gajau Whisker x 2 + 200 Gold'),
(28, 'Jagras Helm', 'Head', 1, 'Great Jagras Hide x2 + Great Jagras Mane x2 + Great Jagras Claw x 2 + Ancient Bone x 1 + 200 Gold'),
(29,'Jagras Mail', 'Body', 1, 'Great Jagras Hide x 2 + Great Jagras Claw x 1 + Great Jagras Scale x 2 + Monster Bone S x 3 + 200 Gold'),
(30, 'Jagras Vambraces', 'Arm', 1, 'Great Jagras Scale x 2 + Great Jagras Hide x 1 + Jagras Hide x 3 + 200 Gold'),
(31, 'Jagras Coil', 'Waist', 1, 'Great Jagras Hide x 1 + Great Jagras Mane x 1 + Great Jagras Scale x 2 + Sharp Claw x 2 + 200 Gold'),
(32, 'Jagras Greaves', 'Legs', 1, 'Great Jagras Scale x 1 + Great Jagras Hide x 1 + Great Jagras Mane x 1 + Jagras Scale x 2 +200 Glod'),
(33, 'Kulu Headpiece', 'Head', 1, 'Kulu-Ya-Ku Scale x 2 + Kulu-Ya-Ku Hide x 1 + Klu-Ya-Ku Plume x 1 + 200 Gold'),
(34, 'Kulu Mail', 'Body', 1, 'Kulu-Ya-Ku Hide x 2 + Kulu-Ya-Ku Plume x 1 + Kulu-Ya-Ku Beak x 1 + Machalite Ore x 2 + 200 Gold'),
(35, 'Kulu Vambraces', 'Arm',  1, 'Kulu-Ya-Ku Scale x 2 + Kulu-Ya-Ku Hide x 1 + Iron Ore x 3 + 200 Gold'),
(36, 'Kulu Coil', 'Waist', 1, 'Kulu-Ya-Ku Hide x 2 + Kulu-Ya-Ku Beak x 1 + Wingdrake Hide x 2 + 200 Gold'),
(37, 'Kulu Greaves', 'Legs', 1, 'Kulu-Ya-Ku Hide x 2 + Kulu-Ya-Ku Scale x 3 + Wingdrake Hide x 2 + 200 Gold'),
(38,'Alloy Helm', 'Head', 2, 'Machalite Ore x 4 + Iron Ore x 4 + Earth Crystal x 2 + 500 Gold'),
(39, 'Alloy Mail', 'Body', 2, 'Machalite Ore x3 + Iron Ore x6 + Earth Crystal x1 + 500 Gold'),
(40, 'Alloy Vambraces', 'Arm', 2, 'Machalite Ore x3 + Iron Ore x6 + Earth Crystal x1 + 500 Gold'),
(41, 'Alloy Coil', 'Waist', 2, 'Machalite Ore x 4 + Iron Ore x 4 + Earth Crystal x 2 + 500 Gold'),
(42, 'Alloy Greaves', 'Legs', 2, 'Machalite Ore x 3 + Iron Ore x 6 + Earth Crystal x 1 + 500 Gold'),
(43, 'Pukei Hood', 'Head', 2, 'Pukei-Pukei Shell x2 + Pukei-Pukei Tail x1 + Pukei-Pukei Quill x2 + Machalite Ore x2 + 500 Gold'),
(44, 'Pukei Mail', 'Body', 2, 'Pukei-Pukei Scale x 2 + Pukei-Pukei Shell x 1 + Iron Ore x 3 + 500 Gold'),
(45, 'Pukei Vambraces', 'Arm', 2, 'Pukei-Pukei Scale x 2 + Pukei-Pukei Shell x 1 + Poison Sac x1 + 500 Gold'),
(46, 'Pukei Coil', 'Waist', 2, 'Pukei-Pukei Shell x3 + Pukei-Pukei Tail x1 + Pukei-Pukei Sac x1 + Poison Sac x1 + 500 Gold'),
(47, 'Pukei Greaves', 'Legs', 2, 'Pukei-Pukei Shell x2 + Pukei-Pukei Sac x1 + Pukei-Pukei Scale x 2 + Monster Bone M x1 + 500 Gold'),
(48, 'Barroth Helm', 'Head', 2, 'Barroth Ridge x 2 + Barroth Tail x 1 + Barroth Claw x 2 + Kestodon Shell x 2 + 500 Gold'),
(49, 'Barroth Mail', 'Body', 2, 'Barroth Shell x 2 + Barroth Ridge x 1 + Barroth Claw x1 + Boulder Bone x 1 + 500 Gold'),
(50, 'Barroth Vambraces', 'Arm', 2, 'Barroth Ridge x 2 + Barroth Tail x 1 + Barroth Claw x 2 + Kestodon Shell x 2 + 500 Gold'),
(51, 'Barroth Coil', 'Waist', 2, 'Barroth Ridge x 2 + Barroth Scalp x 1 + Barroth Shell x 2 + Fertile Mud x 2 + 500 Gold'),
(52, 'Barroth Greaves', 'Legs', 2, 'Barroth Ridge x 2 + Barroth Scalp x 1 + Barroth Shell x 1 + Fertile Mud x 2 + 500 Gold'),
(53, 'Jyura Helm', 'Head', 2, 'Jyuratodus Scale x 2 + Jyuratodus Shell x 1 + Jyuratodus Fin x 1 + Gajau Skin x 3 + 500 Gold'),
(54, 'Jyura Mail', 'Body', 2, 'Jyuratodus Shell x 2 + Jyuratodus Fin x 1 + Jyuratodus Fang x 1 + Aqua Sac x1 + 500 Gold'),
(55, 'Jyura Vambraces', 'Arm', 2, 'Jyuratodus Shell x 2 + Jyuratodus Fang x 1 + Gajau Whisker x 2 + 500 Gold'),
(56, 'Jyura Coil', 'Waist', 2, 'Jyuratodus Scale x 2 + Jyuratodus Shell x 1 + Aqua Sac x1 + 500 Gold'),
(57, 'Jyura Greaves', 'Legs', 2, 'Jyuratodus Fang x 2 + Jyuratodus Shell x 3 + Jyuratodus Fin x 2 + Earth Crystal x 3 + 500 Gold'),
(58, 'Kadachi Helm', 'Head', 2, 'Tobi-Kadachi Pelt x 2 + Tobi-Kadachi Electrode x 2 + Tobi-Kadachi Claw x 1 + Electro Sac x 1 + 500 Gold'),
(59, 'Kadachi Mail', 'Body', 2, 'Tobi-Kadachi Pelt x 2 + Tobi-Kadachi Electrode x 1 + Tobi-Kadachi Membrane x 2 + Wingdrake Hide x 2 + 500 Gold'),
(60, 'Kadachi Vambraces', 'Arm', 2, 'Tobi-Kadachi Pelt x 2 + Tobi-Kadachi Scale x 2 + Tobi-Kadachi Claw x 1 + Monster Bone M x2 + 500 Gold'),
(61, 'Kadachi Coil', 'Waist', 2, 'Tobi-Kadachi Scale x 2 + Tobi-Kadachi Pelt x 1 + Electro Sac x 1 + 500 Gold'),
(62, 'Kadachi Greaves', 'Legs', 2, 'Tobi-Kadachi Scale x 2 + Tobi-Kadachi Pelt x 1 + Warm Pelt x 1 + 500 Gold'),
(63, 'High Metal Helm', 'Head', 3, 'Dragonite Ore x 2 + Machalite Ore x 1 + Iron Ore x 6 + 1500 Gold'),
(64, 'High Metal Mail', 'Body', 3, 'Dragonite Ore x 2 + Machalite Ore x 2 + Earth Crystal x 2 + Sharp Claw x 2 + 1500 Gold'),
(65, 'High Metal Braces', 'Arm', 3, 'Dragonite Ore x 2 + Machalite Ore x 1 + Earth Crystal x 2 + Sharp Claw x 2 + 1500 Gold'),
(66, 'High Metal Coil', 'Waist', 3, 'Dragonite Ore x 2 + Machalite Ore x 1 + Iron Ore x 6 + 1500 Gold'),
(67, 'High Metal Greaves', 'Legs', 3, 'Dragonite Ore x 2 + Machalite Ore x 1 + Iron Ore x 6 + 1500 Gold'),
(68, 'King Beetle Vertex', 'Head', 3, 'Great Hornfly x 1 + Dragonite Ore x 2 + Coral Crystal x 2 + Flame Sac x 2 + 1500 Gold'),
(69, 'King Beetle Thorax', 'Body', 3, 'Great Hornfly x 1 + Earth Crystal x 2 + Coral Crystal x 2 + Poison Sac x 1 + 1500 Gold'),
(70, 'King Beetle Brachia', 'Arm', 3, 'Great Hornfly x 1 + Earth Crystal x 2 + Coral Crystal x 2 + Poison Sac x 1 + 1500 Gold'),
(71, 'King Beetle Elytra', 'Waist', 3, 'Great Hornfly x 1 + Earth Crystal x 2 + Monster Fluid x1 + Electro Sac x1 + 1500 Gold'),
(72, 'King Beetle Crura', 'Legs', 3, 'Great Hornfly x 1 + Dragonite Ore x 2 + Monster Fluid x 3 + Paralysis Sac x1 + 1500 Gold'),
(78, 'Shamos Goggles', 'Head', 3, 'Shamos Hide x 2 + Shamos Scale x 3 + Coral Bone x 1 + Coral Crystal x 1 + 1500 Gold'),
(79, 'Hornetaur Helm', 'Head', 3, 'Hornetaur Head x 1 + Hornetaur Shell x 1 + Machalite Ore x 1 + Monster Fluid x 1 + 1500 Gold'),
(80, 'Hornetaur Mail', 'Body', 3, 'Hornetaur Wing x 2 + Hornetaur Shell x 2 + Dragonite Ore x 2 + Machalite Ore x 2 + 1500 Gold'),
(81, 'Hornetaur Vambraces', 'Arm', 3, 'Hornetaur Wing x 1 + Hornetaur Shell x 1 + Iron Ore x 3 + Machalite Ore x 1 + 1500 Gold'),
(82, 'Hornetaur Coil', 'Waist', 3, 'Hornetaur Wing x 1 + Hornetaur Shell x 1 + Iron Ore x 3 + Machalite Ore x 1 + 1500 Gold'),
(83, 'Hornetaur Greaves', 'Legs', 3, 'Hornetaur Wing x 1 + Hornetaur Shell x 1 + Dragonite Ore x 3 + Monster Fluid x 2 + 1500 Gold'),
(84, 'Anja Helm', 'Head', 3, 'Anjanath Pelt x3 + Anjanath Scale x3 + Anjanath Tail x1 + Flame Sac x1 + 1500 Gold'),
(85, 'Anja Mail', 'Body', 3, 'Anjanath Pelt x3 + Anjanath Fang x2 + Anjanath Nosebone x1 + Anjanath Plate x1 + 1500 Gold'),
(86, 'Anja Vambraces', 'Arm', 3, 'Anjanath Pelt x2 + Anjanath Scale x2 + Anjanath Nosebone x1 + Monster Bone L x2 + 1500 Gold'),
(87, 'Anja Coil', 'Waist', 3, 'Anjanath Scale x2 + Anjanath Pelt x1 + Anjanath Fang x2 + Machalite Ore x2 + 1500 Gold'),
(88, 'Anja Greaves', 'Legs', 3, 'Anjanath Scale x2 + Anjanath Pelt x3 + Flame Sac x1 + Machalite Ore x2 + 1500 Gold'),
(89, 'Rathian Helm', 'Head', 3, 'Rathian Shell x2 + Rathian Scale x3 + Rathian Webbing x2 + Flame Sac x1 + 1500 Gold'),
(90, 'Rathian Mail', 'Body', 3, 'Rathian Scale x2 + Rathian Shell x1 + Rathian Webbing x1 + Ancient Bone x2 + 1500 Gold'),
(91, 'Rathian Vambraces', 'Arm', 3, 'Rathian Shell x2 + Rathian Scale x2 + Rathian Spike x1 + Monster Bone L x2 + 1500 Gold'),
(92, 'Rathian Coil', 'Waist', 3, 'Rathian Scale x2 + Rathian Shell x1 + Rath Wingtalon x 2 + Boulder Bone x 2 + 1500 Gold'),
(93, 'Rathian Greaves', 'Legs', 3, 'Rathian Shell x3 + Rathian Spike x1 + Rath Wingtalon x2 + Rathian Plate x1 + 1500 Gold'),
(94, 'Tzitzi Headgear', 'Head', 3, 'Tzitzi-Ya-Ku Scale x2 + Tzitzi-Ya-Ku Hide x1 + Tzitzi-Ya-Ku Photophore x1 + Coral Crystal x1 + 1500 Gold'),
(95, 'Tzitzi Mail', 'Body', 3, 'Tzitzi-Ya-Ku Hide x3 + Tzitzi-Ya-Ku Claw x2 + Tzitzi-Ya-Ku Photophore x2 + Lightcrystal x1 + 1500 Gold'),
(96, 'Tzitzi Vambracesl', 'Arm', 3, 'Tzitzi-Ya-Ku Hide x2 + Tzitzi-Ya-Ku Photophore x1 + Tzitzi-Ya-Ku Scale x3 + Coral Crystal x2 + 1500 Gold'),
(97, 'Tzitzi Coil', 'Waist', 3, 'Tzitzi-Ya-Ku Hide x2 + Tzitzi-Ya-Ku Claw x2 + Coral Crystal x2 + 1500 Gold'),
(98, 'Tzitzi Greaves', 'Legs', 3, 'Tzitzi-Ya-Ku Scale x2 + Tzitzi-Ya-Ku Hide x1 + Tzitzi-Ya-Ku Claw x1 + 1500 Gold'),
(99, 'Lumu Hat', 'Head', 3, 'Paolumu Scale x2 + Paomulu Webbing x2 + Paolumu Shell x2 + Lightcrystal x1 + 1500 Gold'),
(100, 'Lumu Mail', 'Body', 3, 'Paolumu Scale x2 + Paolumu Shell x1 + Paolumu Pelt x2 + Coral Bone x1 + 1500 Gold'),
(101, 'Lumu Vambraces', 'Arm', 3, 'Paolumu Pelt x2 + Paolumu Scale x1 + Paomulu Webbing x1 + 1500 Gold'),
(102, 'Lumu Coil', 'Waist', 3, 'Paolumu Pelt x2 + Paolumu Scale x1 + Paolumu Shell x1 + 1500 Gold'),
(103, 'Lumu Greaves', 'Legs', 3, 'Paolumu Scale x2 + Paolumu Pelt x2 + Paomulu Webbing x1 + Coral Bone x1 + 1500 Gold'),
(104, 'Girros Mask', 'Head', 3, 'Great Girros Scale x2 + Great Girros Hide x1 + Great Girros Hood x1 + Girros Scale x3 + 1500 Gold'),
(105, 'Girros Mail', 'Body', 3, 'Great Girros Hide x2 + Great Girros Tail x1 + Great Girros Fang x1 + Paralysis Sac x2 + 1500 Gold'),
(106, 'Girros Vambraces', 'Arm', 3, 'Great Girros Scale x2 + Great Girros Hide x1 + Great Girros Fang x2 + 1500 Gold'),
(107, 'Girros Coil', 'Waist', 3, 'Great Girros Hide x2 + Great Girros Tail x1 + Great Girros Hood x1 + Girros Hide x3 + 1500 Gold'),
(108, 'Girros Greaves', 'Legs', 3, 'Great Girros Hide x2 + Great Girros Fang x2 + Great Girros Scale x2 + Monster Bone M x4 + 1500 Gold'),
(109, 'Baan Helm', 'Head', 3, 'Radobaan Shell x3 + Radobaan Oilshell x2 + Wyvern Bonemass x2 + Radobaan Marrow x1 + 1500 Gold'),
(110, 'Baan Mail', 'Body', 3, 'Radobaan Scale x 2 + Radobaan Shell x 1 + Radobaan Oilshell x 1 + Sleep Sac x 1 + 1500 Gold'),
(111, 'Baan Vambraces', 'Arm', 3, 'Radobaan Scale x 2 + Radobaan Shell x 1 + Radobaan Oilshell x 1 + Radobaan Oilshell x1 + 1500 Gold'),
(112, 'Baan Coil', 'Waist', 3, 'Radobaan Scale x 2 + Radobaan Oilshell x1 + Sleep Sac x 1 + 1500 Gold'),
(113, 'Baan Greaves', 'Legs', 3, 'Radobaan Shell x3 + Radobaan Scale x 2 + Wyvern Bonemass x2 + Warped Bone x2 + 1500 Gold'),
(114, 'Ingot Helm', 'Head', 4, 'Dragonite Ore x 2 + Monster Bone + x 1 + Iron Ore x 8 + Machalite Ore x 3 + 3000 Gold');


/* To insert data for QUEST table:*/
--cant use this to insert ARMOR table!
INSERT INTO QUEST(QID,Qname,rewards,quest_type)
VALUES
(101,'Jagras of the Ancient Forest','720 Gold','Slaying'),
(102,'A Kestodon Kerfuffle','1200 Gold','Slaying'),
(103,'The Great Jagras Hunt','1200 Gold','Hunting'),
(201,'Bird-Brained Bandit','1800 Gold','Special'),
(205,'Urgent: Pukei-Pukei Hunt','2520 Gold','Hunting'),
(301,'The Best Kind of Quest','2520 Gold','Special'),
(302,'Sinister Shadows in the Swamp','3240 Gold','Special'),
(305,'Flying Sparks: Tobi-Kadachi','3240 Gold','Hunting'),
(306,'The Encroaching Anjanath','4320 Gold','Hunting'),
(401,'One for the History Books','4320 Gold','Special'),
(405,'Ballooning Problems','4320 Gold','Hunting'),
(407,'Radobaan Roadblock','4320 Gold','Hunting'),
(408,'Legiana:Embodiment of Elegance','5400 Gold','Hunting'),
(501,'Into the Bowels of the Vale','5400 Gold','Special'),
(502,'A Fiery Throne Atop the Forest','5400 Gold','Hunting'),
(503,'Horned Tyrant Below the Sands','5400 Gold','Hunting'),
(504,'A Colossal Task','8280 Gold','Special'),
(601,'Invader in the Waste','7200 Gold','Hunting'),
(605,'Tickled Pink','9000 Gold','Hunting'),
(607,'Old World Monster in the New World','12600 Gold','Special'),
(701,'A Wound and a Thirst','18000 Gold','Slaying'),
(801, 'Kushala Daora, Dragon of Steel', '18000 Gold', 'Slaying'),
(802, 'Teostra the Infernal', '18000 Gold', 'Slaying'),
(803, 'Hellish Fiend Vaal Hazak', '18000 Gold', 'Investigation'),
(804, 'Land of Convergence', '19800 Gold', 'Special'),
(805, 'Beyond the Blasting Scales', '27720 Gold', 'Hunting'),
(806, 'Thunderous Rumble in the Highlands', '21600 Gold', 'Slaying'),
(241, 'Learning the Clutch', '300 Gold', 'Special'),
(151, 'Butting Heads with Nature', '720 Gold', 'Slaying'),
(152, 'A Thicket of Thugs', '720 Gold', 'Slaying'),
(153, "Fungal Flexin' in the Ancient Forest", '720 Gold', 'Delivery'),
(251, 'The Great Glutton', '1800 Gold', 'Hunting'),
(252, 'Camp Crasher', '1800 Gold', 'Hunting'),
(261, 'Snatch the Snatcher', '2520 Gold', 'Capture'),
(262, 'The Pain from Gains', '1080 Gold', 'Hunting'),
(263, 'Exterminator of the Waste', '1080 Gold', 'Hunting'),
(351, 'Scatternut Shortage', '2520 Gold', 'Hunting'),
(352, 'The Current Situation', '3240 Gold', 'Hunting'),
(361, 'Mired in the Spire', '2520 Gold', 'Hunting'),
(362, 'The Piscine Problem', '3240 Gold', 'Hunting'),
(363, 'Prickly Predicament', '1080 Gold', 'Delivery'),
(364, "Gettin' Yolked in the Waste", '1080 Gold', 'Delivery'),
(365, 'Landing the Landslide Wyvern', '3600 Gold', 'Capture'),
(331, 'Special Arena: Pukei-Pukei', '2520 Gold', 'Hunting'),
(332, 'Special Arena: Barroth', '2520 Gold', 'Hunting'),
(333, 'Special Arena: Tobi-Kadachi', '3240 Gold', 'Hunting'),
(451, 'One Helluva Sinus Infection', '4320 Gold', 'Hunting'),
(452, "Gettin' Yolked in the Forest", '3600 Gold', 'Delivery'),
(461, 'Royal Relocation', '4320 Gold', 'Hunting'),
(471, "It's a Crying Shamos", '2520 Gold', 'Hunting'),
(472, 'A Tzitzi for Science', '3240 Gold', 'Hunting'),
(473, "Sorry You're Not Invited", '4320 Gold', 'Hunting'),
(474, 'What a Bunch of Abalone', '3600 Gold', 'Delivery'),
(475, 'White Monster for a White Coat', '5760 Gold', 'Capture'),
(481, 'Persistent Pests', '2520 Gold', 'Hunting'),
(482, 'A Rotten Thing To Do', '3240 Gold', 'Hunting'),
(483, 'A Bone to Pick', '4320 Gold', 'Hunting'),
(484, "On Nightmare's Wings", '2520 Gold', 'Hunting'),
(5003, 'Troubled Troupers', '9000 Gold', 'Hunting'),
(431, 'Special Arena: Anjanath', '4320 Gold', 'Hunting'),
(433, 'Special Arena: Paolumu', '4320 Gold', 'Hunting'),
(434, 'Special Arena: Radobaan', '4320 Gold', 'Hunting'),
(551, 'When Desire Becomes an Obsession', '5400 Gold', 'Hunting'),
(552, 'Redefining the "Power Couple"', '7920 Gold', 'Hunting'),
(561, 'Twin Spires Upon the Sands', '5400 Gold', 'Hunting'),
(571, 'A Humid Headache', '5400 Gold', 'Hunting'),
(572, 'Gone in a Flash', '9000 Gold', 'Hunting'),
(581, 'Scratching the Itch', '5400 Gold', 'Hunting'),
(582, "Man's Best Fiend", '7200 Gold', 'Capture'),
(583, 'The Meat of the Matter', '3600 Gold', 'Delivery'),
(531, 'Special Arena: Legiana', '5400 Gold', 'Hunting'),
(532, 'Special Arena: Odogaron', '5400 Gold', 'Hunting'),
(533, 'Special Arena: Rathalos', '5400 Gold', 'Hunting'),
(534, 'Special Arena: Diablos', '5400 Gold', 'Hunting'),
(641, 'Left Quite the Impression', '8280 Gold', 'Special'),
(651, 'Hard to Swallow', '5400 Gold', 'Hunting'),
(652, 'Googly-eyed Green Monster', '7200 Gold', 'Hunting'),
(653, 'A Hair-Raising Experience', '7200 Gold', 'Hunting'),
(654, "It Can't See You if You Don't Move", '9000 Gold', 'Hunting'),
(655, 'The Sleeping Sylvan Queen', '9000 Gold', 'Hunting'),
(656, 'Stuck in Their Ways', '9360 Gold', 'Capture'),
(661, 'Keep Your Hands to Yourself!', '5400 Gold', 'Hunting'),
(662, 'A Crown of Mud and Anger', '7200 Gold', 'Hunting'),
(663, 'Pukei-Pukei Ambush', '7200 Gold', 'Hunting'),
(665, 'Up to Your Waist in the Waste', '9000 Gold', 'Hunting'),
(666, 'Brown Desert, Green Queen', '9000 Gold', 'Hunting'),
(667, 'Trespassing Troublemaker', '9000 Gold', 'Hunting'),
(671, 'Say Cheese!', '5400 Gold', 'Hunting'),
(672, 'Loop the Paolumu', '7200 Gold', 'Hunting'),
(681, 'A Tingling Taste', '5400 Gold', 'Hunting'),
(682, 'Stuck in a Rut', '5400 Gold', 'Hunting'),
(683, 'Chef Quest! Pumped to Deliver', '5400 Gold', 'Delivery'),
(684, 'Chef Quest! A Rotten Request', '5400 Gold', 'Slaying'),
(691, 'A Meow for Help', '5400 Gold', 'Slaying'),
(692, 'A Scalding Scoop', '6480 Gold', 'Slaying'),
(693, 'Dodogama Drama', '9000 Gold', 'Hunting'),
(694, 'Chef Quest! Gajalaka Lockdown', '5400 Gold', 'Slaying'),
(631, 'Special Arena: HR Pukei-Pukei', '7200 Gold', 'Hunting'),
(632, 'Special Arena: HR Barroth', '7200 Gold', 'Hunting'),
(633, 'Special Arena: HR Tobi-Kadachi', '7200 Gold', 'Hunting'),
(634, 'Special Arena: HR Anjanath', '9000 Gold', 'Hunting'),
(635, 'Special Arena: HR Rathian', '9000 Gold', 'Hunting'),
(636, 'Special Arena: HR Paolumu', '7200 Gold', 'Hunting');


/* To insert data for MONSTER table:*/
--Good to insert!
INSERT INTO MONSTER(M_ID,Mname,Msize,HZV,Mtype,threat_level,Q_ID,Q_name)
VALUES
(1, 'Aptonoth','Small', 'Head' ,'Small Monster', 0, 101,'Jagras of the Ancient Forest'),
(2, 'Jagras','Small','Head','Small Monster', 0, 102,'A Kestodon Kerfuffle'),
(3, 'Mernos','Small','Head','Small Monster', 0, 201,'Bird-Brained Bandit'),
(4, 'Vespoid','Small', 'Head','Small Monster', 0, 405,'Ballooning Problems'),
(5, 'Mosswine','Small', 'Head','Small Monster', 0,103,'The Great Jagras Hunt'),
(6, 'Apceros','Small', 'Head','Small Monster', 0, 201,'Bird-Brained Bandit'),
(7, 'Kestodon','Small','Head' ,'Small Monster', 0, 205,'Urgent: Pukei-Pukei Hunt'),
(8, 'Noios','Small', 'Head','Small Monster', 0, 306,'The Encroaching Anjanath');
(9, 'Gajau','Small', 'Head','Small Monster', 0, 408,'Legiana:Embodiment of Elegance' ),
(10, 'Kelbi','Small', 'Head','Small Monster', 0, 502,'A Fiery Throne Atop the Forest' ),
(11, 'Raphinos','Small', 'Head','Small Monster', 0, 503,'Horned Tyrant Below the Sands' ),
(12, 'Shamos','Small', 'Head','Small Monster', 0, 605,'Tickled Pink' ),
(13, 'Girros','Small', 'Head','Small Monster', 0, 701,'A Wound and a Thirst' ),
(17, 'Great Jagras','Large', 'Head' ,'Fanged Wyvern', 30, 103,'The Great Jagras Hunt'),
(18, 'Kulu-Ya-Kus','Large', 'Head' ,'Bird Wyvern', 50, 205,'Urgent: Pukei-Pukei Hunt'),
(19, 'Pukei-Pukei','Large', 'Head' ,'Bird Wyvern', 20, 301,'The Best Kind of Quest'),
(20, 'Barroth','Large', 'Head' ,'Brute Wyvern', 10, 501,'Into the Bowels of the Vale'),
(21, 'Jyuratodus','Large', 'Head' ,'Piscine Wyvern', 10, 502,'A Fiery Throne Atop the Forest'),
(22, 'Tobi-Kadachi','Large', 'Head' ,'Fanged Wyvern', 10, 503,'Horned Tyrant Below the Sands'),
(23, 'Anjanath','Large', 'Head' ,'Brute Wyvern', 10, 504,'A Colossal Task'),
(24, 'Rathian','Large', 'Head' ,'Flying Wyvern', 30, 601,'Invader in the Waste'),
(25, 'Tzitzi-Ya-Ku','Large', 'Head' ,'Bird Wyvern', 60, 605,'Tickled Pink'),
(26, 'Paolumu','Large', 'Head' ,'Flying Wyvern', 30, 632, 'Special Arena: HR Barroth'),
(27, 'Great Girros','Large', 'Head' ,'Fanged Wyvern', 80, 801, 'Kushala Daora, Dragon of Steel'),
(28, 'Radobaan','Large', 'Head' ,'Brute Wyvern', 40, 802, 'Teostra the Infernal'),
(29, 'Legiana','Large', 'Head' ,'Flying Wyvern', 50, 803, 'Hellish Fiend Vaal Hazak'),
(30, 'Odogaron','Large', 'Head' ,'Fanged Wyvern', 60, 804, 'Land of Convergence'),
(31, 'Rathalos','Large', 'Head' ,'Flying Wyvern', 60, 805, 'Beyond the Blasting Scales'),
(32, 'Diablos','Large', 'Head' ,'Flying Wyvern', 10, 5003, 'Troubled Troupers'),
(33, 'Kirin','Large', 'Head' ,'Elder Dragon', 90, 241, 'Learning the Clutch'),
(34, 'Zorah Magdaros','Large', 'Head' ,'Elder Dragon', 75, 151, 'Butting Heads with Nature'),
(35, 'Dodogama','Large', 'Head' ,'Fanged Wyvern', 15, 152, 'A Thicket of Thugs'),
(36, 'Pink Rathian','Large', 'Head' ,'Flying Wyvern', 70, 401,'One for the History Books'),
(37, 'Bazelgeuse','Large', 'Head' ,'Flying Wyvern', 75, 251, 'The Great Glutton'),
(38, 'Deviljho','Large', 'Head' ,'Brute Wyvern', 80, 252, 'Camp Crasher'),
(39, 'Lavasioth','Large', 'Head' ,'Piscine Wyvern', 20, 261, 'Snatch the Snatcher'),
(40, 'Uragaan','Large', 'Head' ,'Brute Wyvern', 25, 262, 'The Pain from Gains'),
(41, 'Azure Rathalos','Large', 'Head' ,'Flying Wyvern', 55, 263, 'Exterminator of the Waste'),
(42, 'Black Diablos	','Large', 'Head' ,'Flying Wyvern', 95, 351, 'Scatternut Shortage'),
(43, 'Nergigante','Large', 'Head' ,'Elder Dragon', 10, 352, 'The Current Situation'),
(44, 'Teostra','Large', 'Head' ,'Elder Dragon', 15, 361, 'Mired in the Spire'),
(45, 'Kushala Daora','Large', 'Head' ,'Elder Dragon', 80, 362, 'The Piscine Problem'),
(46, 'Vaal Hazak','Large', 'Head' ,'Elder Dragon', 80, 363, 'Prickly Predicament'),
(47, "Xeno'jiiva",'Large', 'Head' ,'Elder Dragon', 85, 364, "Gettin' Yolked in the Waste"),
(48, 'Kulve Taroth','Large', 'Head' ,'Elder Dragon', 90, 365, 'Landing the Landslide Wyvern'),
(49, 'Lunastra','Large', 'Head' ,'Elder Dragon', 55, 331, 'Special Arena: Pukei-Pukei'),
(50, 'Behemoth','Large', 'Head' ,'Elder Dragon', 100, 332, 'Special Arena: Barroth'),
(51, 'Leshen','Large', 'Head' ,'Relict', 100, 333, 'Special Arena: Tobi-Kadachi'),
(52, 'Ancient Leshen','Large', 'Head' ,'Relict', 100, 451, 'One Helluva Sinus Infection'),
(111, 'Beotodus','Large', 'Head' ,'Piscine Wyvern', 100, 452, "Gettin' Yolked in the Forest"),
(112, 'Banbaro','Large', 'Head' ,'Brute Wyvern', 90, 461, 'Royal Relocation'),
(113, 'Viper Tobi-Kadachi','Large', 'Head' ,'Fanged Wyvern', 90, 471, "It's a Crying Shamos"),
(114, 'Nightshade Paolumu','Large', 'Head' ,'Flying Wyvern', 90, 472, 'A Tzitzi for Science'),
(115, 'Coral Pukei-Pukei','Large', 'Head' ,'Bird Wyvern', 90, 473, "Sorry You're Not Invited"),
(116, 'Barioth','Large', 'Head' ,'Flying Wyvern', 80, 474, 'What a Bunch of Abalone'),
(117, 'Nargacuga','Large', 'Head' ,'Flying Wyvern', 60, 475, 'White Monster for a White Coat'),
(118, 'Glavenus','Large', 'Head' ,'Brute Wyvern', 80, 481, 'Persistent Pests'),
(119, 'Tigrex','Large', 'Head' ,'Flying Wyvern', 90, 482, 'A Rotten Thing To Do'),
(120, 'Brachydios','Large', 'Head' ,'Brute Wyvern', 90, 483, 'A Bone to Pick'),
(121, 'Shrieking Legiana','Large', 'Head' ,'Flying Wyvern', 20, 484, "On Nightmare's Wings"),
(122, 'Fulgur Anjanath','Large', 'Head' ,'Brute Wyvern', 20, 5003, 'Troubled Troupers'),
(123, 'Acidic Glavenus','Large', 'Head' ,'Brute Wyvern', 15, 431, 'Special Arena: Anjanath'),
(124, 'Ebony Odogaron','Large', 'Head' ,'Fanged Wyvern', 25, 433, 'Special Arena: Paolumu'),
(125, 'Velkhana','Large', 'Head' ,'Elder Dragon', 50, 434, 'Special Arena: Radobaan'),
(126, 'Seething Bazelgeuse','Large', 'Head' ,'Flying Wyvern', 60, 693, 'Dodogama Drama'),
(127, 'Blackveil Vaal Hazak','Large', 'Head' ,'Elder Dragon', 60, 552, 'Redefining the "Power Couple"'),
(128, 'Namielle','Large', 'Head' ,'Elder Dragon', 60, 561, 'Twin Spires Upon the Sands'),
(129, 'Savage Deviljho','Large', 'Head' ,'Elder Dragon', 75, 571, 'A Humid Headache'),
(130, 'Ruiner Nergigante','Large', 'Head' ,'Elder Dragon', 10, 572, 'Gone in a Flash'),
(131, 'Shara Ishvalda','Large', 'Head' ,'Elder Dragon', 35, 583, 'The Meat of the Matter'),
(132, 'Zinogre','Large', 'Head' ,'Fanged Wyvern', 100, 582, "Man's Best Fiend"),
(133, 'Yian Garuga','Large', 'Head' ,'Bird Wyvern', 100, 504,'A Colossal Task'),
(134, 'Scarred Yian Garuga','Large', 'Head' ,'Bird Wyvern', 10, 701,'A Wound and a Thirst'),
(135, 'Brute Tigrex','Large', 'Head' ,'Flying Wyvern', 90, 655, 'The Sleeping Sylvan Queen'),
(136, 'Gold Rathian','Large', 'Head' ,'Flying Wyvern', 55, 701,'A Wound and a Thirst'),
(137, 'Silver Rathalos','Large', 'Head' ,'Flying Wyvern', 25, 656, 'Stuck in Their Ways'),
(138, 'Rajang','Large', 'Head' ,'Fanged Beast', 75, 661, 'Keep Your Hands to Yourself!'),
(139, "Safi'jiiva",'Large', 'Head' ,'Fanged Wyvern', 95, 662, 'A Crown of Mud and Anger'),
(140, 'Frostfang Barioth','Large', 'Head' ,'Elder Dragon', 80, 663, 'Pukei-Pukei Ambush'),
(142, 'Furious Rajang','Large', 'Head' ,'Fanged Beast', 100, 665, 'Up to Your Waist in the Waste'),
(143, 'Raging Brachydios','Large', 'Head' ,'Brute Wyvern', 10, 666, 'Brown Desert, Green Queen'),
(144, 'Alatreon','Large', 'Head' ,'Elder Dragon', 100, 667, 'Trespassing Troublemaker'),
(145, 'Frostfang Barioth','Large', 'Head' ,'Flying Wyvern', 95, 671, 'Say Cheese!'),
(146, 'Fatalis','Large', 'Head' ,'Elder Dragon', 100, 672, 'Loop the Paolumu');

/* To insert data for WEAPON table:*/
INSERT INTO WEAPON(WID,Wname, Sharpness, Waffinity, weapon_type, Upgrade, Element,Deco_slots, Materials)
VALUES
(1, 'Buster Sword I','Yellow', 0,'Great Sword','Y','Blast', 0, 'Iron Ore x1 + 200 Gold'),
(2, 'Buster Sword II','Green', 0,'Great Sword','Y','Blast', 0, 'Iron Ore x2 + 200 Gold'),
(3, 'Buster Sword III','Green', 0,'Great Sword','N','Blast', 0, 'Earth Crystal x2 + Machalite Ore x2 + Iron Ore x5 + 1000 Gold'),
(4, 'Buster Blade I','Yellow', 0,'Great Sword','Y','Blast', 0, 'Iron Ore x1 + 200 Gold'),
(5, 'Buster Blade II','Green', 0,'Great Sword','Y','Blast', 0, 'Iron Ore x2 + 200 Gold'),
(6, 'Buster Blade III','Green', 0,'Great Sword','N','Poison', 0, 'Earth Crystal x2 + Machalite Ore x2 + Iron Ore x5 + 1000 Gold'),
(7, 'Chrome Razor I','Blue', 0,'Great Sword','Y','Poison', 0, 'Fucium Ore x8 + Carbalite Ore x5 + Dragonite Ore  x10 + Dragonvein Crystal x3 + 16000 Gold'),
(8, 'Chrome Razor II','Blue', 0,'Great Sword','Y','Poison', 0, 'Elder Dragon Blood x2 + Fucium Ore x13 + Carbalite Ore x20 + Fire stone x1 + 32000 Gold'),/* violent WID constraint(Primary Key)!*/
(89, 'Iron Katana I','Yellow', 0, 'Long Sword','Y','Blast', 0, 'Iron Ore x1 + 200 Gold'),
(2001, 'Defender Great Sword I','Green', 0,'Great Sword','Y','Blast', 0, 'Iron Ore x1'),
(2002, 'Defender Great Sword II','Blue', 0,'Great Sword','Y','Blast', 0, ' Anjanath Scale x1 + 1000 Gold'),
(2003, 'Defender Great Sword III','Blue', 0,'Great Sword','Y','Blast', 0, 'Commendation x1 + 3000 Gold'),
(2004, 'Defender Great Sword IV','Blue', 0,'Great Sword','Y','Blast', 0, 'Pink Rathian Scale x1 + 6000 Gold'),
(2005, 'Defender Great Sword V','White', 0,'Great Sword','Y','Blast', 0, ' Immortal Dragonscale x1 + 10000 Gold'),
(2006, 'Chrome Deathscythe I','White',0,'Great Sword', 'Y', 'Poison', 2, 'Eltalite Ore x6 + Carbalite Ore x10 + Firecell Stone x2 + Purecrystal x1 + 16000 Gold'),
(2007, 'Chrome Deathscythe II','White',0,'Great Sword', 'Y', 'Poison', 2, ' Monster Slogbone x3 + Eltalite Ore x4 + Meldspar Ore x2 + Bathycite Ore x2 + 24000 Gold'),
(2008, 'Chrome Deathscythe III','White',0,'Great Sword', 'N', 'Poison', 2,'Pure Dragon Blood x3 + Eltalite Ore x6 + Meldspar Ore x3 + Purecrystal x1 + 56000 Gold'),
(9, 'Nergal Judicator','Blue',0,'Great Sword', 'Y', 'Dragon', 1,'Nergigante Talon x3 + Nergigante Regrowth Plate x4 + Nergigante Tailx2 + Nergigante Carapace x2 + 32000 Gold'),
(10, "Purgation's Atrocity",'Blue',0,'Great Sword', 'N', 'Dragon', 1, "Xeno'jiiva Horn x2 + Nergigante Horn + x5 + Nergigante Talon x5 + Nergigante Gem x1 + 56000 Gold"),
(2009, 'Ruinous Atrocity','White',0,'Great Sword', 'N', 'Dragon', 1, 'Annihilating Greathorn x3 + Nergigante Hardclaw x4 + Eternal Regrowth Plate x5 + Large Elder Dragon Gem x1'),
(11, 'Thunder Blade I','Green',0,'Great Sword', 'Y', 'Thunder', 0, 'Dragonite Ore x5 + Tobi-Kadachi Electrode x1 + Tobi-Kadachi Claw x2 + Electro Sac x1 + 2000 Gold'),
(12, 'Thunder Blade II','Green',0,'Great Sword', 'N', 'Thunder', 0, ' Monster Bone + x2 + Tobi-Kadachi Electrode x2 + Tobi-Kadachi Membrane x2 + Coral Crystal x3 + 4000 Gold'),
(13, 'Lightning Punisher I','Green',0,'Great Sword', 'Y', 'Thunder', 1, 'Carbalite Ore x5 + Tobi-Kadachi Scale + x4 + Tobi-Kadachi Pelt + x3 + Vespoid Innerwing x3 + 6000 Gold'),
(14, 'Lightning Punisher II','Blue',0,'Great Sword', 'Y', 'Thunder', 1, 'Fucium Ore x5 + Tobi-Kadachi Electrode + x2 + Tobi-Kadachi Membrane x4 + Thunder Sac x3 + 16000 Gold'),
(15, 'Lightning Punisher III','Blue',0,'Great Sword', 'N', 'Thunder', 1, 'Elder Dragon Blood x3 + Tobi-Kadachi Electrode+ x4 + Tobi-Kadachi Claw + x6 + Wyvern Gem x1 + 32000 Gold'),
(2010, 'Lightning Punisher IV','White',0,'Great Sword', 'Y', 'Thunder', 1, 'Tobi-Kadachi Hardclaw x1 + Tobi-Kadachi Shard x2 + Tobi-Kadachi Thickfur x2 + Lightning Sac x1 + 16000 Gold'),
(2011, 'Severing Bolt I','White',0,'Great Sword', 'Y', 'Thunder', 1, 'Zinogre Hardclaw x3 + Zinogre Deathly Shocker x2 + Zinogre Cortex x5 + Lightning Sac x3 + 32000 Gold'),
(2012, 'Severing Bolt II','White',0,'Great Sword', 'N', 'Thunder', 2, 'Zinogre Hardhorn x3 + Zinogre Electrofur+ x4 + Fulgurbug x5 + Zinogre Skymerald x1 + 56000 Gold'),
(16, 'Freeze Blade I','Green',0,'Great Sword', 'Y', 'Ice', 0, 'Legiana Claw x3 + Legiana Scale x4 + Frost Sac x2 + Coral Crystal x3 + 4000 Gold'),
(17, 'Freeze Blade II','Green',0,'Great Sword', 'N', 'Ice', 1, 'Carbalite Ore x3 + Legiana Tail Webbing x2 + Legiana Webbing x3 + Shamos Scale+ x5 + 6000 Gold'),
(18, 'Frost Blaze I','Green',0,'Great Sword', 'Y', 'Ice', 1, 'Fucium Ore x5 + Legiana Scale + x5 + Legiana Wing x3 + Freezer Sac x3 + 16000 Gold'),
(19, 'Frost Blaze II','Green',0,'Great Sword', 'N', 'Ice', 1, 'Elder Dragon Blood x3 + Legiana Claw + x5 + Legiana Hide + x3 + Wyvern Gem x1 + 32000 Gold'),
(2013, 'Frost Blaze III','Blue',0,'Great Sword', 'N', 'Ice', 1, 'Gracium x2 + Eltalite Ore x4 + Cryo Sac x1 + Wulg Thickfur x3 + 16000 Gold'),
(2014, 'Icicle Fang','White',20,'Great Sword', 'Y', 'Ice', 0, 'Barioth Hardclaw x3 + Barioth Cortex x4 + Cryo Sac x4 + Frozen Bone x3 + 24000 Gold'),
(2015, 'Icicle Fang+','White',30,'Great Sword', 'Y', 'Ice', 0, 'Obsidian Icetalon x2 + Amber Hardfang x3 + Barioth Greatspike x3 + Large Wyvern Gem x1 + 32000 Gold'),
(2016, 'Paladire','White',35,'Great Sword', 'N', 'Ice', 0, 'Velkhana Hardclaw x2 + Barioth Hardclaw x4 + Amber Hardfang x2 + Large Elder Dragon Bone x5 + 356000 Gold'),
(3222, 'Glacial Demon','White',15,'Great Sword', 'N', 'Ice', 0, 'Frostfang Ticket x3 + Silverwhite Frostfang x3 + Bergcrusher Claw x2 + Large Wyvern Gem x1'),
(20, 'Jagras Blade I','Green',0,'Great Sword', 'Y', 'Blast', 0, 'Buster Sword II + Great Jagras Claw x1 + Great Jagras Hide x1 + Great Jagras Scale x3 + Sharp Claw x1 + 1000 Gold'),
(21, 'Jagras Blade II','Green',0,'Great Sword', 'Y', 'Blast', 0, 'Great Jagras Claw x2 + Great Jagras Mane x2 + Coral Bone x2 + Tzitzi-Ya-Ku Claw x3 + 2000 Gold'),
(22, 'Jagras Blade III','Green',0,'Great Sword', 'N', 'Blast', 0, 'Monster Bone+ x3 + Great Jagras Scale x5 + Great Jagras Claw x3 + Great Jagras Mane x3 + 4000 Gold'),
(23, 'Jagras Hacker I','Green',0,'Great Sword', 'Y', 'Water', 2, 'Great Jagras Scale + x6 + Great Jagras Claw + x4 + Great Jagras Mane x6 + Piercing Claw x5 + 6000 Gold'),
(24, 'Jagras Hacker II','Blue',0,'Great Sword', 'Y', 'Water', 2, 'Great Jagras Scale + x6 + Great Jagras Claw + x4 + Great Jagras Mane x6 + Piercing Claw x5 + 16000 Gold'),
(25, 'Jagras Hacker III','Blue',0,'Great Sword', 'N', 'Water', 1, 'Vaal Hazak Talon x2 + Great Jagras Claw + x8 + Great Jagras Hide + x6 + Novacrystal x1 + 32000 Gold'),
(2017, 'Jagras Deathclaw I','Blue',0,'Great Sword', 'Y', 'Water', 1, 'Great Jagras Shard x2 + Great Jagras Hardclaw x1 + Great Jagras Mane + x2 + Fey Wyvern Gem x1 + 16000 Gold'),
(2018, 'Jagras Deathclaw II','White',0,'Great Sword', 'N', 'Water', 1, 'Monster Slogbone x3 + Great Jagras Hardclaw x3 + Great Jagras Thickhide x3 + Tough Claw x 3 + 24000 Gold'),
(2019, 'Mammoth Greataxe I','Blue',0,'Great Sword', 'Y', 'Ice', 1, 'Banbaro Great Horn x1 + Banbaro Cortex x2 + Banbaro Chine x2 + Monster Toughbone x3 + 20000 Gold'),
(2020, 'Mammoth Greataxe II','Blue',0,'Great Sword', 'N', 'Ice', 1, 'Monster Solidbone x3 + Banbaro Great Horn x 3 + Banbaro Lash x2 + Dragonbone Artifact x1 + 32000 Gold'),
(26, 'Girros Blade I','Green',15,'Great Sword', 'Y', 'Paralysis', 0, 'Great Girros Fang x1 + Great Girros Scale x3 + Girros Fang x3 + 2000 Gold'),
(27, 'Girros Blade II','Green',15,'Great Sword', 'N', 'Paralysis', 0, 'Diablos Fang x2 + Great Girros Fang x3 + Great Girros Hood x2 + Paralysis Sac x2 + 4000 Gold'),
(28, "Malady's Kiss I",'Blue',20,'Great Sword', 'Y', 'Paralysis', 0, ' Carbalite Ore x6 + Omniplegia Sac x6 + Great Girros Hood + x3 + Great Girros Fang + x5 + 12000 Gold'),
(29, "Malady's Kiss II",'Blue',20,'Great Sword', 'Y', 'Paralysis', 0, 'Blos Medulla x1 + Great Girros Fang + x2 + Great Girros Hood + x 2 + Omniplegia Sac x4 + 16000 Gold'),
(30, "Malady's Kiss III",'Blue',20,'Great Sword', 'N', 'Paralysis', 0, 'Vaal Hazak Fang + x2 + Great Girros Fang + x5 + Great Girros Hood + x3 + Bird Wyvern Gem x 1 + 32000 Gold'),
(2021, 'Naaga Guillotine I','Blue',20,'Great Sword', 'Y', 'Paralysis', 0, 'Great Girros Hardfang x2 + Great Girros Lash x1 + Ultraplegia Sac x2 + Tough Claw x2 + 16000 Gold'),
(2022, 'Naaga Guillotine II','Blue',25,'Great Sword', 'N', 'Paralysis', 0, 'Odogaron Hardfang x2 + Great Girros Shard x4 + Great Girros Hardhood x2 + Fey Wyvern Gem x1 + 24000 Gold'),
(2023, 'Hidden Blade I','White',20,'Great Sword', 'Y', 'Poison', 0, 'Nargacuga Hardfang x2 + Nargacuga Shard x3 + Nargacuga Tailspear x2 + Meldspar Ore x1 + 24000 Gold'),
(2024, 'Hidden Blade II','Purple',25,'Great Sword', 'N', 'Poison', 1, 'Fulgur Anjanath Hardfang x2 + Nargacuga Cutwing + x3 + Nargacuga Lash x2 + Nargacuga Mantle x1 + 32000 Gold'),
(31, 'Lava Blaze I','Blue',0,'Great Sword', 'Y', 'Fire', 2, 'Lavasoith Fin + x2 + Lavasioth Fang + x2 + Lavasioth Scale + x4 + 16000 Gold'),
(32, 'Lava Blaze II','Blue',0,'Great Sword', 'N', 'Fire', 2, 'Teostra Mane x2 + Lavasioth Fin + x3 + Lavasioth Fang + x3 + Wyvern Gem x1 + 32000 Gold'),
(2025, 'Pyre Cleaver I','Blue',0,'Great Sword', 'Y', 'Fire', 2, 'Lavasioth Grandfin x1 + Lavasioth Hardfang x2 + Lavasioth Shard x3 + Barnos Hardclaw x2 + 24000 Gold'),
(2026, 'Pyre Cleaver II','Blue',0,'Great Sword', 'N', 'Fire', 2, 'Azure Rathalos Cortex x2 + Lavasioth Grandfin x2 + Lavasioth Hardfang x2 + Monster Solidbone x3 + 32000 Gold'),
(2027, 'Glavenus Blaze I','White',0,'Great Sword', 'Y', 'Fire', 1, 'Glavenus Hardfang x2 + Glavenus Shard x4 + Molten Bursa x2 + Eltalite Ore x6 + 24000 Gold'),
(2028, 'Glavenus Blaze II','White',0,'Great Sword', 'N', 'Fire', 1, 'Ebony Odogaron Hardfang x2 + Glavenus Hellshell x3 + Glavenus Tailedge x2 + Glavenus Mantle x1 + 32000 Gold'),
(33, 'Blooming Blade I','Green',0,'Great Sword', 'Y', 'Poison', 0, 'Pukei-Pukei Quill x2 + Pukei Scale x3 + Poison Sac x1 + 1000 Gold'),
(34, 'Blooming Blade II','Green',0,'Great Sword', 'Y', 'Poison', 0, 'Coral Crystal x3 + Pukei-Pukei Sac x2 + Pukei-Pukei Shell x3 + Pukei-Pukei Tail x1 + 2000 Gold'),
(35, 'Blooming Blade III','Green',0,'Great Sword', 'N', 'Poison', 0, 'Monster Bone + x2 + Pukei-Pukei Quill x4 + Pukei-Pukei Sac x 2 + Poison Sac x 2 + 1000 Gold'),
(36, 'Datura Blaze I','Blue',0,'Great Sword', 'Y', 'Poison', 2, 'Pukei-Pukei Scale + x3 + Pukei-Pukei Wing x2 + Toxin Sac x2 + Quality Bone x3 + 6000 Gold'),
(37, 'Datura Blaze II','Blue',0,'Great Sword', 'Y', 'Poison', 2, 'Pukei-Pukei Quill x2 + Pukei Scale x3 + Poison Sac x1 + 1000 Gold'),
(38, 'Datura Blaze III','Blue',0,'Great Sword', 'N', 'Poison', 2, 'Vaal Hazak Wing x2 + Pukei-Pukei Sac + x4 + Pukei-Pukei Wing x6 + Bird Wyvern Gem x1 + 1000 Gold'),
(2029, 'Datura Hellspine I','White',0,'Great Sword', 'Y', 'Poison', 2, 'Deadly Poison Sac x4 + Fey Wyvern Gem x1 + Pukei-Pukei Shard x6 + Pukei-Pukei Fellwing x4 + 16000 Gold'),
(2030, 'Datura Hellspine II','White',0,'Great Sword', 'N', 'Poison', 2, 'Monster Slogbone x3 + Rathian Surpike x2 + Large Pukei-Pukei Sac x2 + Pukei-Pukei Lash x1 + 24000 Gold'),
(2031, 'Nyx Razor I','White',0,'Great Sword', 'Y', 'Sleep', 1, ' Nightshade Paolumu Thickfur x3 + Paolumu Cortex x2 + Nightshade Paolumu Fellwing x2 + Torpor Sac x1 + 20000 Gold'),
(2032, 'Nyx Razor II','Blue',0,'Great Sword', 'N', 'Sleep', 1, 'Black Diablos Chine x2 + Nightshade Paolumu Shard x5 + Nightshade Paolumu Fellwing x3 + Large Wyvern Gem x1 + 32000 Gold'),
(39, 'Flame Blade I','Green',10,'Great Sword', 'Y', 'Fire', 0, 'Rathalos Scale x1 + Rathalos Webbing x2 + Flame Sac x2 + Rathalos Marrow x1 + 4000 Gold'),
(40, 'Flame Blade II','Green',10,'Great Sword', 'N', 'Fire', 0, 'Rathalos Scale x6 + Rathalos Tail x2 + Rathalos Plate x1 + Inferno Sac x3 + 8000 Gold'),
(41, 'Red Wing','Blue',15,'Great Sword', 'Y', 'Fire', 1, 'Rathalos Scale x6 + Rathalos Carapace x4 + Rathalos Wing x2 + Rathalos Medulla x1 + 24000 Gold'),
(42, 'Blue Wing','Blue',15,'Great Sword', 'Y', 'Fire', 1, 'Azure Rathalos Scale + x6 + Azure Rathalos Carapace x4 + Azure Rathalos Wing x3 + Wyvern Gem x1 + 32000 Gold'),
(43, 'Rathalos Glinsword','Blue',15,'Great Sword', 'Y', 'Fire', 1, 'Teostra Horn + x2 + Azure Rathalos Scale + x8 + Azure Rathalos Tail x3 + Rathalos Ruby x1 + 56000 Gold'),
(2033, 'Rathalos Glinsword+','Blue',15,'Great Sword', 'N', 'Fire', 1, 'Rathalos Shard x6 + Rathalos Cortex x4 + Rathalos Fellwing x2 + Rath Wingtalon + x4 + 24000 Gold'),
(2034, 'Rathalos Gleamsword','White',25,'Great Sword', 'N', 'Fire', 1, 'Silver Rathalos Shard x8 + Silver Rathalos Cortex x4 + Silver Rathalos Lash x3 + Rath Gleam x2'),
(44, 'Bone Blade I','Orange',0,'Great Sword', 'Y', 'Elementless', 0, 'Monster Bone S x2 + 200 Gold'),
(45, 'Bone Blade II','Orange',0,'Great Sword', 'Y', 'Elementless', 0, 'Monster Bone S x2 + 200 Gold'),
(46, 'Bone Blade III','Orange',0,'Great Sword', 'N', 'Elementless', 0, 'Monster Bone S x2 + Ancient Bone x1 + 1000 Gold'),
(47, 'Bone Slasher I','Green',0,'Great Sword', 'Y', 'Elementless', 0, 'Monster BoneL x1 + Monster Bone M x5 + Boulder Bone x2 + 2000 Gold'),
(48, 'Bone Slasher II','Green',0,'Great Sword', 'Y', 'Elementless', 0, 'Monster Bone+ x2 + Monster BoneL x1 +  Sturdy Bone x4 + 4000 Gold'),
(49, 'Bone Slasher III','Orange',0,'Great Sword', 'N', 'Elementless', 0, 'Monster Keenbone x2 + Monster Bone+ x2 + Quality Bone x2 + 1000 Gold'),
(50, 'Giant Jawblade I','Blue',0,'Great Sword', 'Y', 'Ice', 1, 'Brutal Bone x4 + Dragonbone Relic x1 + Monster Keenbone x10 + Monster Hardbone x4 + 32000 Gold'),
(51, 'Giant Jawblade II','Blue',0,'Great Sword', 'N', 'Ice', 1, ' Elder Dragon Bone x4 + Monster Hardbone x6 + Quality Bone x20 + Dragonbone Relic x1 + 32000 Gold'),
(2036, "Ogre's Jaw I",'Blue',0,'Great Sword', 'Y', 'Ice', 1, 'Thick Bone x6 + Quality Bone x8 + Dragonbone Artifact x1 + Monster Toughbone x4 + 32000 Gold'),
(2037, "Ogre's Jaw II",'Blue',0,'Great Sword', 'Y', 'Ice', 1, 'Monster Solidbone x2 + Monster Slogbone x3 + Thick Bone x4 + Monster Essence x2 + 32000 Gold'),
(2038, "Ogre's Jaw III",'Blue',0,'Great Sword', 'N', 'Ice', 1, 'Large Elder Dragon Bone x3 + Monster Solidbone x4 + Thick Bone x6 + Dragonbone Artifact x1 + 32000 Gold'),
(2039, "Icewing",'White',0,'Great Sword', 'Y', 'Ice', 1, 'Crystal Shard x4 + Velkhana Hardclaw x2 + Velkhana Lash x2 + Purecrystal x1 + 56000 Gold'),
(2040, "Icewing",'White',0,'Great Sword', 'N', 'Ice', 1, 'Shara Ishvalda Tenderclaw x3 + Velkhana Crownhorn x4 + Velkhana Hardclaw x4 + Velkhana Crystal x1 + Purecrystal x1 + 80000 Gold'),
(2041, "Tiger Jawblade",'White',-20,'Great Sword', 'Y', 'Blast', 0, 'Tigrex Hardclaw x3 + Tigrex Shard x4 + Monster Slogbone x3 + Thick Bone x5 + 24000 Gold'),
(2042, "Tiger Jawblade +",'White',-20,'Great Sword', 'Y', 'Blast', 0, 'Blackcurl Stouthorn x1 + Tigrex Hardfang x3 + Tigrex Lash x2 + Tigrex Mantle x1 + 32000 Gold'),
(2043, "Tigrex Great Sword",'White',-20,'Great Sword', 'Y', 'Blast', 0, 'Daora Hardclaw x2 + Tigrex Hardfang x2 + Tigrex Cortex x4 + Pure Dragon Blood x5 + 56000 Gold'),
(2044, "Accursed Blade",'Purple',-30,'Great Sword', 'Y', 'Sleep', 0, 'Brute Tigrex Hardclaw x3 + Brute Tigrex Shard x5 + Brute Tigrex Hardfang x2 + Large Wyvern Gem x1'),
(2045, "Wildbite",'Purple',-30,'Great Sword', 'N', 'Sleep', 0, 'Tempered Ebonjaw x5 + Brute Tigrex Hardclaw x4 + Brute Tigrex Hardfang x3 + Tigrex Mantle x1'),
(1203,'Empress Daggers "Blaze"','White', 20, 'Dual Blades', 'N', 'Blast', 2, 'Research Commission Ticket x1 + Lunastra Horn x2 + Teostra Horn+ x 3 + Bazelgeuse Gem x1 + 56000 Gold'),--Having issue
(1204,'Empress Daggers "Blaze"','White', 20, 'Dual Blades', 'N', 'Blast', 2, 'Lunastra Shard x4 + Lunastra Hardhorn x4 + Lunastra Mane+ x4 + Large Elder Dragon Gem x1 + 80000 Gold'),--Having issue
(2076, 'Soulfire Edge "Styx"','White',0,'Dual Blades', 'N', 'Blast', 3, 'Lunastra Shard x4 + Lunastra Lash x2 + Elder Spiritvein Bone x5 + Large Elder Dragon Gem x1 + 80000 Gold'),
(90, 'Iron Katana II','Green', 0, 'Long Sword','Y','Blast', 0, 'Iron Ore x2 + 200 Gold'),
(91, 'Iron Katana III','Green', 0, 'Long Sword','N','Blast', 0, 'Earth Crystal x2 + Machalite Ore x2 + Iron Ore x5 + 1000 Gold'),
(1192, 'Empress Galea "Ruin"', 'White',0,'Great Sword', 'Y', 'Blast', 2, 'Research Commission Ticket x1 + Lunastra Wing x3 + Nergigante Horn+ x3 + Nergigante Gem x1 + 56000 Gold'),
(1155, 'Fatal Bite', 'Blue',-20,'Sword & Shield', 'Y', 'Dragon', 0, 'Deviljho Scale x6 + Deviljho Talon x2 + Deviljho Tallfang x 3 + Deviljho Saliva x2 + 24000 Gold'),
(614, 'Rath Gunlance I', 'Green',15,'Gunlance', 'Y', 'Fire', 0, 'Rathalos Scale x1 + Rathalos Webbing x2 + Flame Sac x 2 + Rathalos Marrow x 2 + 4000 Gold'),
(2667, 'Hidden Axe', 'White',10,'Switch Axe', 'Y', 'Poison', 0, 'Nargacuga Hardfang x2 + Nargacuga Shard x3 + Nargacuga Tailspear x2 + Meldspar Ore x1 + 24000 Gold'),
(2761, 'Wild Force I', 'White',10,'Charge Blade', 'Y', 'Blast', 1, 'Thick Bone x2 + Quality Bone x2 + Monster Hardbone x4 + Frozen Bone x1'),
(831, '	Iron Blade I', 'Orange',0,'Insect Glaive', 'Y', 'Elementless', 0, 'Iron Ore x1 + 200 Gold'),
(912, '	Chain Blitz I', 'Orange',0,'Light Bowgun', 'Y', 'Ammo', 0, 'Iron Ore x1 + 200 Gold'),
(996, '	Iron Assault I', 'Orange',0,'Heavy Bowgun', 'Y', 'Ammo', 0, 'Iron Ore x1 + 200 Gold');


/* To insert data for HUNTER table:*/
INSERT INTO HUNTER(HID, Hname, Palico_name, Q_ID, Q_name)
VALUES
(1, 'Happy Hunter','Happyson',302,'Sinister Shadows in the Swamp'),
(2, 'Slay Hunter','Cutie',501,'Into the Bowels of the Vale'),
(3, 'Faker','Zed',701,'A Wound and a Thirst'),
(4, 'DollorQ','QQ',405,'Ballooning Problems'),
(5, 'Great Hunter','Useless cat',205,'Urgent: Pukei-Pukei Hunt'),
(6, 'Iron kid','Hilton',504,'A Colossal Task'),
(7, 'Peter Hunter','Hunter P',701,'A Wound and a Thirst'),
(8, 'Aiden', 'Whiskers', 302,'Sinister Shadows in the Swamp'),
(9, 'Bryce', 'Mittens', 302,'Sinister Shadows in the Swamp'),
(10, 'Caitlyn', 'Furry', 302,'Sinister Shadows in the Swamp'),
(11, 'Derek', 'Paws', 302,'Sinister Shadows in the Swamp'),
(12, 'Evelyn', 'Scratch', 302,'Sinister Shadows in the Swamp'),
(13, 'Sarah', 'Meowster', 101, 'Jagras of the Ancient Forest'),
(14, 'David', 'Felyne', 101, 'Jagras of the Ancient Forest'),
(15,'Nina', 'Whiskers', 101, 'Jagras of the Ancient Forest'),
(16, 'Jason', 'Kitty', 101, 'Jagras of the Ancient Forest'),
(17, 'Karen', 'Mittens', 101, 'Jagras of the Ancient Forest'),
(18, 'Bob', 'Purrfect', 101, 'Jagras of the Ancient Forest'),
(19, 'Claire', 'Purrfect', 101, 'Jagras of the Ancient Forest'),
(20, 'Dylan', 'Whiskers', 101, 'Jagras of the Ancient Forest'),
(21, 'Emma', 'Pawpaw', 101, 'Jagras of the Ancient Forest'),
(22, 'Frank', 'Mittens', 701,'A Wound and a Thirst'),
(23, 'Grace', 'Kitty', 504,'A Colossal Task'),
(24, 'Henry', 'Neko', 504,'A Colossal Task'),
(25, 'Isabelle', 'Felyne', 701,'A Wound and a Thirst'),
(26, 'Jack', 'Furrball', 431, 'Special Arena: Anjanath'),
(27, 'Kendra', 'Whiskers', 431, 'Special Arena: Anjanath'),
(28, 'Liam', 'Purrfect', 701,'A Wound and a Thirst'),
(29, 'Mia', 'Muffin', 431, 'Special Arena: Anjanath'),
(30, 'Noah', 'Purrfect', 701,'A Wound and a Thirst'),
(31, 'Olivia', 'Kitty', 701,'A Wound and a Thirst'),
(32, 'Peter', 'Neko', 701,'A Wound and a Thirst'),
(33, 'Quinn', 'Pawpaw', 431, 'Special Arena: Anjanath'),
(34, 'Riley', 'Furrball', 431, 'Special Arena: Anjanath'),
(35, 'Sophia', 'Whiskers', 431, 'Special Arena: Anjanath'),
(36, 'Thomas', 'Mittens', 636, 'Special Arena: HR Paolumu'),
(37, 'John', 'Fluffy', 101, 'Jagras of the Ancient Forest'),
(38, 'Mary', 'Whiskers', 636, 'Special Arena: HR Paolumu'),
(39, 'David', 'Mittens', 636, 'Special Arena: HR Paolumu'),
(40, 'Samantha', 'Whiskers', 636, 'Special Arena: HR Paolumu'),
(41, 'Markus', 'Fang', 694, 'Chef Quest! Gajalaka Lockdown'),
(42, 'Emily', 'Meowster', 694, 'Chef Quest! Gajalaka Lockdown'),
(43, 'Trevor', 'Claws', 805, 'Beyond the Blasting Scales'),
(44, 'Avery', 'Muffin', 801, 'Kushala Daora, Dragon of Steel'),
(45, 'Lincoln', 'Purrfect', 804, 'Land of Convergence'),
(46, 'Nate', 'Mittens', 804, 'Land of Convergence'),
(47, 'Sophia', 'Saber', 331, 'Special Arena: Pukei-Pukei'),
(48, 'David', 'Shadow', 331, 'Special Arena: Pukei-Pukei'),
(49, 'Maggie', 'Fluff', 331, 'Special Arena: Pukei-Pukei'),
(50, 'Archer', 'Whiskers', 102, 'A Kestodon Kerfuffle'),
(51, 'Brawler', 'Mittens', 331, 'Special Arena: Pukei-Pukei'),
(52, 'Caster', 'Socks', 331, 'Special Arena: Pukei-Pukei'),
(53, 'Defender', 'Boots', 605, 'Tickled Pink'),
(54, 'Explorer', 'Tiger', 252, 'Camp Crasher'),
(55,'Lin', 'Whiskers', 101, 'Jagras of the Ancient Forest'),
(56, 'Kai', 'Fluffball', 331, 'Special Arena: Pukei-Pukei'),
(57, 'Hiro', 'Noodle', 205, 'Urgent: Pukei-Pukei Hunt'),
(58, 'Mia', 'Shadow', 302, 'Sinister Shadows in the Swamp'),
(59, 'Sophie', 'Sprinkles', 407, 'Radobaan Roadblock'),
(60,'Max', 'Fang', 408, 'Legiana:Embodiment of Elegance'),
(61,'Emma', 'Mittens', 503, 'Horned Tyrant Below the Sands'),
(62,'Alex', 'Claws', 805, 'Beyond the Blasting Scales'),
(63,'Avery', 'Socks', 802, 'Teostra the Infernal'),
(64,'Lucas', 'Boots', 803, 'Hellish Fiend Vaal Hazak'),
(65,'Bob', 'Whiskers', 101, 'Jagras of the Ancient Forest'),
(66,'Alice', 'Mittens', 102, 'A Kestodon Kerfuffle'),
(67,'Charlie', 'Boots', 103, 'The Great Jagras Hunt'),
(68,'Diana', 'Furball', 201, 'Bird-Brained Bandit'),
(69,'Ethan', 'Whiskers', 205, 'Urgent: Pukei-Pukei Hunt'),
(70, 'Frank', 'Socks', 301, 'The Best Kind of Quest'),
(71, 'Gabrielle', 'Boots', 302, 'Sinister Shadows in the Swamp'),
(72, 'Henry', 'Furball', 305, 'Flying Sparks: Tobi-Kadachi'),
(73, 'Isabelle', 'Mittens', 306, 'The Encroaching Anjanath'),
(74, 'Jacob', 'Whiskers', 401, 'One for the History Books'),
(75, 'Kate', 'Socks', 405, 'Ballooning Problems'),
(76, 'Liam', 'Furball', 407, 'Radobaan Roadblock'),
(77, 'Mia', 'Boots', 408, 'Legiana: Embodiment of Elegance'),
(78, 'Noah', 'Socks', 501, 'Into the Bowels of the Vale'),
(79, 'Olivia', 'Whiskers', 502, 'A Fiery Throne Atop the Forest'),
(80, 'Peter', 'Boots', 503, 'Horned Tyrant Below the Sands'),
(81, 'Quinn', 'Socks', 504, 'A Colossal Task'),
(82, 'Riley', 'Furball', 601, 'Invader in the Waste'),
(83, 'Samuel', 'Mittens', 605, 'Tickled Pink'),
(84, 'Taylor', 'Boots', 252, 'Camp Crasher'),
(85, 'Ursula', 'Furball', 701, 'A Wound and a Thirst'),
(86, 'Victor', 'Mittens', 801, 'Kushala Daora, Dragon of Steel'),
(87, 'Wendy', 'Socks', 802, 'Teostra the Infernal'),
(88, 'Xander', 'Whiskers', 803, 'Hellish Fiend Vaal Hazak'),
(89, 'Yara', 'Boots', 804, 'Land of Convergence'),
(90, 'Zane', 'Socks', 805, 'Beyond the Blasting Scales'),
(91, 'Abigail', 'Whiskers', 672, 'Loop the Paolumu'),
(92, 'Benjamin', 'Furball', 241, 'Learning the Clutch'),
(93, 'Caroline', 'Mittens', 151, 'Butting Heads with Nature'),
(94, 'David', 'Boots', 152, 'A Thicket of Thugs'),
(95, 'Elizabeth', 'Socks', 205,'Urgent: Pukei-Pukei Hunt'),
(96, 'Finn', 'Whiskers', 251, 'The Great Glutton'),
(97, 'Georgia', 'Furball', 252, 'Camp Crasher'),
(98, 'Hugo', 'Mittens', 261, 'Snatch the Snatcher'),
(99, 'Ingrid', 'Boots', 262, 'The Pain from Gains'),
(100, 'Jack', 'Socks', 263, 'Exterminator of the Waste'),
(101, 'Katie', 'Whiskers', 351, 'Scatternut Shortage'),
(102, 'Landon', 'Furball', 352, 'The Current Situation');

/* To insert data for ITEM table:*/
INSERT INTO ITEM(IID, Iname, Amount, I_type)
VALUES
    (1, 'Potion', 10, 'Liquid'),
	(2, 'Mega Potion', 10, 'Liquid'),
	(3, 'Max Potion', 2, 'Pellets'),
	(4, 'Ancient Potion', 1, 'Pellets'),
	(5, 'Antidote', 10, 'Liquid'),
	(6, 'Herbal Medicine', 5, 'Pellets'),
	(7, 'Nulberry', 10, 'Seed'),
	(8, 'Energy Drink', 10, 'Liquid'),
	(9, 'Ration', 10, 'Meat'),
	(10, 'Rare Steak', 10, 'Meat'),
	(11, 'Well-done Steak', 10, 'Meat'),
	(12, 'Burnt Meat', 10, 'Meat'),
	(13, 'Cool Drink', 5, 'Liquid'),
	(1059, 'Hot Drink', 5, 'Liquid'),
	(14, 'Nutrients', 5, 'Liquid'),
	(15, 'Mega Nutrients', 5, 'Liquid'),
	(16, 'Immunizer', 10, 'Liquid'),
	(17, 'Astera Jerky', 5, 'Meat'),
	(18, 'Dash Juice', 5, 'Liquid'),
	(19, 'Might Seed', 10, 'Seed'),
	(20, 'Demondrug', 5, 'Liquid'),
	(21, 'Mega Demondrug', 5, 'Liquid'),
	(22, 'Might Pill', 5, 'Pellets'),
	(23, 'Adamant Seed', 10, 'Seed'),
	(24, 'Armorskin', 5, 'Liquid'),
	(25, 'Mega Armorskin', 5, 'Liquid'),
	(26, 'Adamant Pill', 5, 'Pellets'),
	(27, 'Lifepowder', 3, 'Sac'),
	(1060, 'Dust of Life', 2, 'Sac'),
	(28, 'Herbal Powder', 3, 'Sac'),
	(29, 'Demon Powder', 3, 'Sac'),
	(30, 'Hardshell Powder', 3, 'Sac'),
	(31, 'Honey', 10, 'Webbing'),
	(32, 'Herb', 10, 'Herb'),
	(33, 'Antidote Herb', 10, 'Herb'),
	(34, 'Fire Herb', 20, 'Herb'),
	(35, 'Flowfern', 20, 'Herb'),
	(36, 'Snow Herb', 20, 'Herb'),
	(37, 'Sleep Herb', 10, 'Herb'),
	(38, 'Ivy', 10, 'Herb'),
	(1061, 'Hot Pepper', 10, 'Herb'),
	(1062, 'Gloamgrass Bud', 4, 'Herb'),
	(39, 'Smokenut', 10, 'Seed'),
	(40, 'Dragonfell Berry', 10, 'Seed'),
	(41, 'Blue Mushroom', 10, 'Mushroom'),
	(42, 'Mandragora', 10, 'Mushroom'),
	(43, 'Nitroshroom', 20, 'Mushroom'),
	(44, "Devil\'s Blight", 10, 'Mushroom'),
	(45, 'Parashroom', 10, 'Mushroom'),
	(46, 'Toadstool', 10, 'Mushroom'),
	(47, 'Exciteshroom', 10, 'Mushroom'),
	(48, 'Chillshroom', 10, 'Mushroom'),
	(49, 'Bitterbug', 10, 'Bug'),
	(50, 'Flashbug', 10, 'Bug'),
	(51, 'Godbug', 10, 'Bug'),
	(52, 'Thunderbug', 10, 'Bug'),
	(53, 'Baitbug', 10, 'Bait'),
	(54, 'Kelbi Horn', 99, 'Fang'),
	(55, 'Dash Extract', 20, 'Liquid'),
	(56, 'Nourishing Extract', 20, 'Liquid'),
	(57, 'Screamer Sac', 10, 'Sac'),
	(58, 'Catalyst', 5, 'Sac'),
	(59, 'Tranq Bomb', 8, 'Smoke'),
	(60, 'Flash Pod', 3, 'Slinger'),
	(61, 'Screamer Pod', 3, 'Slinger'),
	(62, 'Dung Pod', 10, 'Slinger'),
	(63, 'Smoke Bomb', 3, 'Smoke'),
	(64, 'Poison Smoke Bomb', 5, 'Smoke'),
	(65, 'Farcaster', 1, 'Smoke'),
	(1339, 'Banishing Ball', 10, 'Smoke'),
	(66, 'Raw Meat', 10, 'Meat'),
	(67, 'Poisoned Meat', 10, 'Meat'),
	(68, 'Tinged Meat', 10, 'Meat'),
	(69, 'Drugged Meat', 10, 'Meat'),
	(70, 'Gunpowder', 20, 'Sac'),
	(71, 'Small Barrel', 10, 'Barrel'),
	(72, 'Barrel Bomb', 10, 'BarrelBomb'),
	(73, 'Bounce Bomb', 5, 'BarrelBomb'),
	(74, 'Mega Bounce Bomb', 5, 'BarrelBomb'),
	(75, 'Large Barrel', 5, 'Barrel'),
	(76, 'Large Barrel Bomb', 2, 'BarrelBomb'),
	(77, 'Mega Barrel Bomb', 2, 'BarrelBomb'),
	(78, 'Spider Web', 10, 'Web'),
	(79, 'Net', 10, 'Web'),
	(80, 'Trap Tool', 2, 'TrapTool'),
	(81, 'Pitfall Trap', 1, 'Trap'),
	(82, 'Shock Trap', 1, 'Trap'),
	(83, 'Rolled-up Dung', 20, 'Dung'),
	(84, 'Dung', 10, 'Dung'),
	(85, 'Arowana Bait', 10, 'Bait'),
	(86, 'Gunpowderfish Bait', 10, 'Bait'),
	(87, 'Goldenfish Bait', 10, 'Bait'),
	(88, 'Boomerang', 5, 'Boomerang'),
	(89, 'Binoculars', 1, 'Binoculars'),
	(90, 'Powercharm', 1, 'Sac'),
	(91, 'Powertalon', 1, 'Fang'),
	(92, 'Armorcharm', 1, 'Sac'),
	(93, 'Armortalon', 1, 'Fang'),
	(94, 'Needleberry', 99, 'Husk'),
	(95, 'Blastnut', '30', 'Husk'),
	(96, 'Dragonstrike Nut', 5, 'Husk'),
	(97, 'Slashberry', '30', 'Husk'),
	(98, 'Latchberry', 99, 'Husk'),
	(99, 'Bomberry', 5, 'Husk'),
	(100, 'Flamenut', '80', 'Seed'),
	(101, 'Blazenut', '60', 'Seed'),
	(102, 'Gunpowder Level 2', '80', 'Sac'),
	(103, 'Gunpowder Level 3', '80', 'Sac'),
	(1209, 'Blossom Fireworks', 10, 'BarrelBomb'),
	(1210, 'Twilight Fireworks', 10, 'BarrelBomb'),
	(1211, 'Harvest Fireworks', 10, 'BarrelBomb'),
	(1212, 'Star Fireworks', 10, 'BarrelBomb'),
	(1213, 'Appreciation Fireworks', 10, 'BarrelBomb'),
	(114, 'Empty Phial', 99, 'EmptyBottle'),
	(104, 'Whetfish Fin', 10, 'Scale'),
	(105, 'Whetfish Fin+', 5, 'Scale'),
	(106, 'Sushifish Scale', 10, 'Scale'),
	(107, 'Great Sushifish Scale', 5, 'Scale'),
	(108, 'Gunpowderfish Scale', 5, 'Scale'),
	(109, 'Great Gunpowderfish Scale', 5, 'Scale'),
	(110, 'Burst Arowana Scale', 5, 'Scale'),
	(111, 'Great Burst Arowana Scale', 5, 'Scale'),
	(112, 'Bomb Arowana Scale', 5, 'Scale'),
	(113, 'Great Bomb Arowana Scale', 5, 'Scale');


/* To insert data for EQUIPMENT table:*/
INSERT INTO EQUIPMENT(HID, Hname, AID, Aname, WID, Wname)
VALUES
(1, 'Happy Hunter', 2, 'Leather Mail', 1, 'Buster Sword I'),
(2, 'Slay Hunter', 3, 'Leather Gloves', 3, 'Buster Sword III'),
(3, 'Faker', 5, 'Leather Trousers', 7, 'Chrome Razor I'),
(4, 'DollorQ', 8, 'Chainmail Gloves', 4, 'Buster Blade I'),
(5, 'Great Hunter', 11, "Hunter's Headgear", 91, 'Iron Katana III' ),
(6, 'Iron kid', 17, 'Bone Mail', 6, 'Buster Blade III' ),
(7, 'Peter Hunter', 17, 'Bone Mail', 6, 'Buster Blade III' ),
(8, 'Aiden', 32, 'Jagras Greaves', 1, 'Buster Sword I'),
(9, 'Bryce', 41, 'Alloy Coil', 1155, 'Fatal Bite'),
(10, 'Caitlyn', 48, 'Barroth Helm', 11, 'Thunder Blade I'),
(11, 'Derek', 21, 'Vespoid Helm', 11, 'Thunder Blade I'),
(12, 'Evelyn', 14, "Hunter's Coil", 11, 'Thunder Blade I'),
(13, 'Sarah', 16, 'Bone Helm', 1, 'Buster Sword I'),
(14, 'David', 27, 'Gajau Boots', 11, 'Thunder Blade I'),
(15,'Nina', 39, 'Alloy Mail', 1155, 'Fatal Bite'),
(16, 'Jason', 56, 'Jyura Coil', 11, 'Thunder Blade I'),
(17, 'Karen', 61, 'Kadachi Coil', 1, 'Buster Sword I'),
(18, 'Bob', 102, 'Lumu Coil', 11, 'Thunder Blade I'),
(19, 'Claire', 104, 'Girros Mask', 1155, 'Fatal Bite'),
(20, 'Dylan', 97, 'Tzitzi Coil', 1155, 'Fatal Bite'),
(21, 'Emma',92, 'Rathian Coil', 1, 'Buster Sword I'),
(22, 'Frank',27, 'Gajau Boots', 11, 'Thunder Blade I'),
(23, 'Grace',14, "Hunter's Coil",1155, 'Fatal Bite'),
(24, 'Henry',102, 'Lumu Coil', 1, 'Buster Sword I'),
(25, 'Isabelle',102, 'Lumu Coil', 614, 'Rath Gunlance I'),
(26, 'Jack', 27, 'Gajau Boots', 614, 'Rath Gunlance I'),
(27, 'Kendra',102, 'Lumu Coil', 1, 'Buster Sword I'),
(28, 'Liam', 14, "Hunter's Coil", 2008, 'Chrome Deathscythe III'),
(29, 'Mia', 61, 'Kadachi Coil',  2008, 'Chrome Deathscythe III'),
(30, 'Noah', 27, 'Gajau Boots', 614, 'Rath Gunlance I'),
(31, 'Olivia',27, 'Gajau Boots', 614, 'Rath Gunlance I'),
(32, 'Peter',14, "Hunter's Coil",1155, 'Fatal Bite'),
(33, 'Quinn',61, 'Kadachi Coil', 1, 'Buster Sword I'),
(34, 'Riley',61, 'Kadachi Coil', 1155, 'Fatal Bite'),
(35, 'Sophia',14, "Hunter's Coil", 2008, 'Chrome Deathscythe III'),
(36, 'Thomas',27, 'Gajau Boots',  2008, 'Chrome Deathscythe III'),
(37, 'John', 97, 'Tzitzi Coil', 2008, 'Chrome Deathscythe III'),
(38, 'Mary', 97, 'Tzitzi Coil', 2008, 'Chrome Deathscythe III'),
(39, 'David',14, "Hunter's Coil",1, 'Buster Sword I'),
(40, 'Samantha',97, 'Tzitzi Coil', 2008, 'Chrome Deathscythe III'),
(41, 'Markus',97, 'Tzitzi Coil',614, 'Rath Gunlance I'),
(42, 'Emily',97, 'Tzitzi Coil',614, 'Rath Gunlance I'),
(43, 'Trevor',14, "Hunter's Coil",1, 'Buster Sword I'),
(44, 'Avery',97, 'Tzitzi Coil',1155, 'Fatal Bite'),
(45, 'Lincoln',97, 'Tzitzi Coil',1155, 'Fatal Bite'),
(46, 'Nate',14, "Hunter's Coil", 2008, 'Chrome Deathscythe III'),
(47, 'Sophia', 97, 'Tzitzi Coil', 2008, 'Chrome Deathscythe III'),
(48, 'David', 87, 'Anja Coil', 1, 'Buster Sword I'),
(49, 'Maggie',87, 'Anja Coil',   2008, 'Chrome Deathscythe III'),
(50, 'Archer', 87, 'Anja Coil',  2008, 'Chrome Deathscythe III'),
(51, 'Brawler',14, "Hunter's Coil", 2008, 'Chrome Deathscythe III'),
(52, 'Caster', 78, 'Shamos Goggles',  2008, 'Chrome Deathscythe III'),
(53, 'Defender',78, 'Shamos Goggles', 1, 'Buster Sword I'),
(54, 'Explorer',87, 'Anja Coil',  2008, 'Chrome Deathscythe III'),
(55,'Lin',14, "Hunter's Coil", 2008, 'Chrome Deathscythe III'),
(56, 'Kai',78, 'Shamos Goggles', 1155, 'Fatal Bite'),
(57, 'Hiro',87, 'Anja Coil',  2008, 'Chrome Deathscythe III'),
(58, 'Mia',78, 'Shamos Goggles', 1, 'Buster Sword I'),
(59, 'Sophie',78, 'Shamos Goggles', 2009, 'Ruinous Atrocity'),
(60,'Max',14, "Hunter's Coil",2009, 'Ruinous Atrocity'),
(61,'Emma', 63, 'High Metal Helm', 1155, 'Fatal Bite'),
(62,'Alex', 87, 'Anja Coil', 1, 'Buster Sword I'),
(63,'Avery',63, 'High Metal Helm', 2009, 'Ruinous Atrocity'),
(64,'Lucas',87, 'Anja Coil', 2009, 'Ruinous Atrocity'),
(65,'Bob', 14, "Hunter's Coil",2009, 'Ruinous Atrocity'),
(66,'Alice',63, 'High Metal Helm', 614, 'Rath Gunlance I'),
(67,'Charlie',87, 'Anja Coil', 1, 'Buster Sword I'),
(68,'Diana',87, 'Anja Coil', 614, 'Rath Gunlance I'),
(69,'Ethan',63, 'High Metal Helm', 614, 'Rath Gunlance I'),
(70, 'Frank', 87, 'Anja Coil', 1155, 'Fatal Bite'),
(71, 'Gabrielle',14, "Hunter's Coil",2009, 'Ruinous Atrocity'),
(72, 'Henry',63, 'High Metal Helm', 1, 'Buster Sword I'),
(73, 'Isabelle', 87, 'Anja Coil', 2009, 'Ruinous Atrocity'),
(74, 'Jacob', 63, 'High Metal Helm', 2009, 'Ruinous Atrocity'),
(75, 'Kate', 63, 'High Metal Helm', 2009, 'Ruinous Atrocity'),
(76, 'Liam', 87, 'Anja Coil', 2009, 'Ruinous Atrocity'),
(77, 'Mia', 14, "Hunter's Coil",1, 'Buster Sword I'),
(78, 'Noah', 63, 'High Metal Helm', 2009, 'Ruinous Atrocity'),
(79, 'Olivia',46, 'Pukei Coil',2009, 'Ruinous Atrocity'),
(80, 'Peter', 46, 'Pukei Coil',2009, 'Ruinous Atrocity'),
(81, 'Quinn', 46, 'Pukei Coil',1, 'Buster Sword I'),
(82, 'Riley', 46, 'Pukei Coil',2009, 'Ruinous Atrocity'),
(83, 'Samuel',46, 'Pukei Coil',2009, 'Ruinous Atrocity'),
(84, 'Taylor',14, "Hunter's Coil",1, 'Buster Sword I'),
(85, 'Ursula',87, 'Anja Coil', 1, 'Buster Sword I'),
(86, 'Victor',46, 'Pukei Coil',1, 'Buster Sword I'),
(87, 'Wendy', 46, 'Pukei Coil',1, 'Buster Sword I'),
(88, 'Xander',46, 'Pukei Coil',1, 'Buster Sword I'),
(89, 'Yara', 46, 'Pukei Coil',1, 'Buster Sword I'),
(90, 'Zane',87, 'Anja Coil', 1, 'Buster Sword I'),
(91, 'Abigail', 14, "Hunter's Coil",2009, 'Ruinous Atrocity'),
(92, 'Benjamin', 87, 'Anja Coil', 2009, 'Ruinous Atrocity'),
(93, 'Caroline', 87, 'Anja Coil', 1, 'Buster Sword I'),
(94, 'David', 87, 'Anja Coil', 1, 'Buster Sword I'),
(95, 'Elizabeth',87, 'Anja Coil', 1, 'Buster Sword I'),
(96, 'Finn', 14, "Hunter's Coil",1, 'Buster Sword I'),
(97, 'Georgia',87, 'Anja Coil', 2009, 'Ruinous Atrocity'),
(98, 'Hugo', 87, 'Anja Coil', 2009, 'Ruinous Atrocity'),
(99, 'Ingrid', 14, "Hunter's Coil",2009, 'Ruinous Atrocity'),
(100, 'Jack', 87, 'Anja Coil', 2009, 'Ruinous Atrocity'),
(101, 'Katie',14, "Hunter's Coil",2009, 'Ruinous Atrocity'),
(102, 'Landon', 14, "Hunter's Coil",1, 'Buster Sword I');


/* To insert data for ARMOR_SKILL table:*/
INSERT INTO ARMOR_SKILL(ASID, ASname, ASmax_lvl, ASAvailabilities, AID, Aname)
VALUES
(1, 'Hunger Resistance', 1, "Expands your scoutflies' detection range.", 1, 'Leather Headgear'),
(6, 'Master Gatherer',1, 'Speeds up gathering and prevents knockbacks while gathering.', 6, 'Chainmail Headgear'),
(11, 'Scoutfly Range Up',1, "Expands your scoutflies' detection range.", 11, "Hunter's Headgear"),
(12, 'Slinger Capacity',1, "Level 1: Increases the loading capacity for slinger collected from the ground or plants.\n Level 2: In addition, increases the loading capacity for some slinger ammo dropped by monsters.\n Level 3: In addition, increases the loading capacity for all slinger ammo dropped by monsters.\n Level 4: Increases the loading capacity for the slinger ammo collected from the ground or plants even more (requires Slinger Ammo Secret) Iceborne only\n Level 5: Increases the loading capacity for all slinger ammo. (Iceborne only)", 12, "Hunter's Mail"),
(13, 'Stealth', 1, 'Level 1: Makes it 30% easier for Monsters to lose sight of you.\n Level 2: Makes it 50% easier for Monsters to lose sight of you.\n Level 3: Makes it 70% easier for Monsters to lose sight of you.', 13, "Hunter's Vambraces"),
(14, 'Scenthound', 1, 'Level 1: Increases gauge fill rate by 50%.', 14, "Hunter's Coil"),
(15, 'BBQ Master', 1, 'Level 1: Makes it easier to cook well-done steaks.', 15, "Hunter's Greaves"),
(16, 'Health Boost', 1, 'Health +15 \n Level 2: Health +30 \nLevel 3: Health +50', 16, 'Bone Helm'),
(17, 'Attack Boost', 1, 'Level 1: Attack +3\n Level 2: Attack +6\n Level 3: Attack +9\n Level 4: Attack +12 Affinity +5%\n Level 5: Attack +15 Affinity +5%\n Level 6: Attack +18 Affinity +5%\n Level 7: Attack +21 Affinity +5%', 17, 'Bone Mail'),
(18, 'Slugger', 1, 'Level 1: Stun power +20% \n Level 2: Stun power +30% \n Level 3: Stun power +40% \n Level 4: Stun power +50% (Iceborne only) \n Level 5: Stun power +60% (Iceborne only)', 18, 'Bone Vambraces'),
(19, 'Horn Maestro', 1, 'Level 1: Extends melody effect duration and increases health recovery \n Level 2: Greatly increases the effect duration of hunting horn melodies (Iceborne only)', 19, 'Bone Coil'),
(20, 'Entomologist', 1, 'Level 1: Increases the chances of a corpse being left behind. \n Level 2: Greatly increases the chances of a corpse being left behind. \n Level 3: Makes it so corpses will always be left behind.', 20, 'Bone Greaves'),
(21, "Quick Sheath",1, "Level 1: Slightly increases sheathing speed. \n Level 2: Moderately increases sheathing speed. \n Level 3: Greatly increases sheathing speed.", 21, "Vespoid Helm"),
(22, "Windproof", 1, "Level 1: Slightly reduces the effects of minor wind pressure.\n Level 2: Reduces the effects of minor wind pressure.\n Level 3: Negates minor wind pressure.\n Level 4: Negates minor wind pressure and reduces the effects of major wind pressure.\n Level 5: Negates minor and major wind pressure.", 22, "Vespoid Mail"),
(23, 'Paralysis Attack', 1, 'Level 1: Paralysis buildup +5% Bonus: +10 \n Level 2: Paralysis buildup +10% Bonus: +10 \n Level 3: Paralysis buildup +20% Bonus: +10 \n Level 4: Paralysis buildup +30% Bonus: +10 (Iceborne only)', 23, 'Vespoid Vambraces'),
(24, 'Paralysis Resistance', 1, 'Level 1: Reduces the duration of paralysis by 30%. \n Level 2: Reduces the duration of paralysis by 60%. \n Level 3: Prevents paralysis.', 24, 'Vespoid Coil'),
(25, 'Honey Hunter', 1, 'Level 1: One extra honey per gather.', 25, "Vespoid Greaves"),
(26, 'Affinity Sliding', 1,'Level 1: +30% Affinity for 30 seconds after sliding.' , 26, 'Kestodon Guards'),
(27, 'Aquatic/Polar Mobility', 1, 'Level 1: Prevents lowered movement speed. \n Level 2: Increases your evade window and prevents lowered movement speed. \n Level 3: Greatly increases your evade window and prevents lowered movement speed.', 27, 'Gajau Boots'),
(28, 'Speed Eating', 1, 'Level 1: Eat food, drink, and quick use (such as Nulberry) Items 16% faster. \n Level 2: Eat food and drink Items 46% faster, and quick use items 28% faster. \n Level 3: Eat food and drink Items 64% faster, and quick use items 38% faster.', 28, 'Jagras Helm'),
(29, 'Intimidator', 1, "Level 1: Discourages small monsters from engaging you even if you've been spotted. \n Level 2: Highly discourages small monsters from engaging you even if you've been spotted. \n Level 3: Prevents most small monsters from engaging you even if you've been spotted.", 30, 'Jagras Vambraces'),
(30, 'Palico Rally', 1, 'Level 1: Increases Palico attack power and defense by 5% \n Level 2: Increases Palico attack power and defense by 10% \n Level 3: Increases Palico attack power and defense by 15% \n Level 4: Increases Palico attack power and defense by 20% \n Level 5: Increases Palico attack power and defense by 25%', 31, 'Jagras Coil'),
(31, 'Fortify', 1, 'Level 1: Increases attack by 10% and defense by 15% with each use. (Duration limit is 50 minutes since 6.02)', 32, 'Jagras Greaves'),
(32, 'Speed Crawler', 1, 'Level 1: Increases movement speed while crouching.', 33, 'Kulu Headpiece'),
(33, 'Fire Resistance', 1, 'Level 1: +6 Fire Resistance. \n Level 2: +12 Fire Resistance. \n Level 3: +20 Fire Resistance and +10 Defense.', 34, 'Kulu Mail'),
(34, 'Stamina Surge', 1, 'Level 1: Stamina recovery speed +10% \n Level 2: Stamina recovery speed +20% \n Level 3: Stamina recovery speed +30%', 35, 'Kulu Vambraces'),
(35, 'Pro Transporter', 1, 'Level 1: Increases movement speed while transporting and reduces downtime on landings.', 36, 'Kulu Coil'),
(36, 'Item Prolonger', 1, 'Level 1: Item effect duration +10% \n Level 2: Item effect duration +25% \n Level 3: Item effect duration +50%', 37, 'Kulu Greaves'),
(37, 'Critical Eye', 1, 'Level 1: +5% Affinity \n Level 2: +10% Affinity \n Level 3: +15% Affinity \n Level 4: +20% Affinity \n Level 5: +25% Affinity \n Level 6: +30% Affinity \n Level 7: +40% Affinity', 38,'Alloy Helm'),
(38, 'Windproof', 1, 'Level 1: Slightly reduces the effects of minor wind pressure. \n Level 2: Reduces the effects of minor wind pressure. \n Level 3: Negates minor wind pressure. \n Level 4: Negates minor wind pressure and reduces the effects of major wind pressure. \n Level 5: Negates minor and major wind pressure.', 38,'Alloy Helm'),
(39, 'Water Resistance', 1, 'Level 1: +6 Water Resistance. \n Level 2: +12 Water Resistance. \n Level 3: +20 Water Resistance and +10 Defense.', 39, 'Alloy Mail'),
(40, 'Defense Boost', 1, 'Level 1: +5 Defense \n Level 2: +10 Defense \n Level 3: +5% Defense and Bonus +10. \n Level 4: +5% Defense, Bonus +20 and +3 to All Elemental Resistances \n Level 5: +8% Defense, Bonus +20 and +3 to All Elemental Resistances \n Level 6: +8% Defense, Bonus +35 and +5 to All Elemental Resistances \n Level 7: +10% Defense, Bonus +35 and +5 to All Elemental Resistances', 40, 'Alloy Vambraces'),
(41, 'Poison Resistance', 1, 'Level 1: Reduces the duration of poison by 30%. \n Level 2: Reduces the duration of poison by 60%. \n Level 3: Prevents poison.', 41, 'Alloy Coil'),
(42, 'Speed Sharpening	', 1, 'Level 1: Removes one cycle from the sharpening process. \n Level 2: Removes two cycles from the sharpening process. \n Level 3: Removes three cycles from the sharpening process.', 42, 'Alloy Greaves'),
(43, 'Survival Expert', 1, 'Level 1: Interactables restore an additional 50 health. \n Level 2: Interactables restore an additional 80 health. \n Level 3: Interactables restore an additional 100 health.', 43, 'Pukei Hood'),
(44, 'Item Prolonger', 1, 'Level 1: Item effect duration +10% \n Level 2: Item effect duration +25% \n Level 3: Item effect duration +50%', 44, 'Pukei Mail'),
(45, 'Poison Resistance', 1, 'Level 1: Reduces the duration of poison by 30%. \n Level 2: Reduces the duration of poison by 60%. \n Level 3: Prevents poison.', 45, 'Pukei Vambraces'),
(46, 'Poison Attack', 1, 'Level 1: Poison buildup +5% Bonus: +10 \n Level 2: Poison buildup +10% Bonus: +10 \n Level 3: Poison buildup +20% Bonus: +10 \n Level 4: Poison buildup +30% Bonus: +10 (Iceborne only)', 46, 'Pukei Coil'),
(47, 'Botanist', 1, 'Level 1: One extra consumable herb item per gather. \n Level 2: One extra consumable herb, fruit, nut, or seed item per gather. \n Level 3: One extra consumable herb, fruit, nut, seed, or insect item per gather. \n Level 4: One extra consumable herb, fruit, nut, seed, insect, or mushroom item per gather.', 47, 'Pukei Greaves'),
(48, 'Guard', 1, ' Level 1: Slightly decreases the impact of attacks. \n Level 2: Slightly decreases the impact of attacks and reduces stamina depletion by 15%. \n Level 3: Greatly decreases the impact of attacks and reduces stamina depletion by 15%. \n Level 4: Greatly decreases the impact of attacks and reduces stamina depletion by 30%. \n Level 5: Massively decreases the impact of attacks and reduces stamina depletion by 50%.', 48, 'Barroth Helm'),
(49, 'Stamina Thief', 1, 'Level 1: Exhaust power +20% \n Level 2: Exhaust power +30% \n Level 3: Exhaust power +40% \n Level 4: Exhaust power +50% (Iceborne only) \n Level 5: Exhaust power +60% (Iceborne only)', 49, 'Barroth Mail'),
(50, 'Marathon Runner', 1, 'Level 1: Reduces continuous stamina depletion by 15%. \n Level 2: Reduces continuous stamina depletion by 30%. \n Level 3: Reduces continuous stamina depletion by 50%.', 50, 'Barroth Vambraces'),
(51, 'Muck Resistance', 1, 'Level 1: Reduces limits on movement speed and evasion.', 51, 'Barroth Coil'),
(52, 'Stun Resistance', 1, 'Level 1: Reduces Stun duration by 60% (value changed in patch 6.02) \n Level 2: Reduces Stun duration by 90% (value changed in patch 6.02) \n Level 3: Prevents Stun', 52, 'Barroth Greaves'),
(53, 'Aquatic/Polar Mobility', 1, 'Level 1: Prevents lowered movement speed. \n Level 2: Increases your evade window and prevents lowered movement speed. \n Level 3: Greatly increases your evade window and prevents lowered movement speed.', 53, 'Jyura Helm'),
(54, 'Muck Resistance', 1, 'Level 1: Reduces limits on movement speed and evasion.', 54, 'Jyura Mail'),
(55, 'Water Attack', 1, 'Level 1: +30 Water Attack. \n Level 2: +60 Water Attack. \n Level 3: +100 Water Attack. \n Level 4: +5% Water Attack and +100 Water Attack. \n Level 5: +10% Water Attack and +100 Water Attack. \n Level 6: +20% Water Attack and +100 Water Attack.', 55, 'Jyura Vambraces'),
(56, 'Ice Resistance', 1, 'Level 1: +6 Ice Resistance. \n Level 2: +12 Ice Resistance. \n Level 3: +20 Ice Resistance and +10 Defense.', 56, 'Jyura Coil'),
(57, 'Focus', 1, 'Level 1: Increases gauge fill rate by 5% and reduces charge times by 5%. \n Level 2: Increases gauge fill rate by 10% and reduces charge times by 10%. \n Level 3: Increases gauge fill rate by 20% and reduces charge times by 15%.', 57, 'Jyura Greaves'),
(58, 'Constitution', 1, 'Level 1: Reduces fixed stamina depletion by 10%. \n Level 2: Reduces fixed stamina depletion by 20%. \n Level 3: Reduces fixed stamina depletion by 30%. \n Level 4: Reduces fixed stamina depletion by 40%. \n Level 5: Reduces fixed stamina depletion by 50%.', 58, 'Kadachi Helm'),
(59, 'Jump Master', 1, 'Level 1: Negates knockback during jumps.', 59, 'Kadachi Mail'),
(60,  'Evade Extender', 1, 'Level 1: Slightly extends evasion distance. \n Level 2: Extends evasion distance. \n Level 3: Greatly extends evasion distance.', 60, 'Kadachi Vambraces'),
(61, 'Thunder Attack', 1, 'Level 1: +30 Thunder Attack. \n Level 2: +60 Thunder Attack. \n Level 3: +100 Thunder Attack. \n Level 4: +5% Thunder Attack and +100 Thunder Attack. \n Level 5: +10% Thunder Attack and +100 Thunder Attack. \n Level 6: +20% Thunder Attack and +100 Thunder Attack.', 61, 'Kadachi Coil'),
(62, 'Thunder Resistance', 1, 'Level 1: +6 Thunder Resistance. \n Level 2: +12 Thunder Resistance. \n Level 3: +20 Thunder Resistance and +10 Defense.', 62, 'Kadachi Greaves'),
(63, 'Ice Resistance', 1, 'Level 1: +6 Ice Resistance. \n Level 2: +12 Ice Resistance. \n Level 3: +20 Ice Resistance and +10 Defense.', 63, 'High Metal Helm'),
(64, 'Earplugs', 1, 'Level 1: Slightly reduces the effects of weak monster roars \n Level 2: Reduces the effects of weak monster roars \n Level 3: Nullifies weak monster roars \n Level 4: Nullifies weak monster roars and reduces the effects of strong monster roars \n Level 5: Nullifies weak and strong monster roars', 64, 'High Metal Mail'),
(65, 'Defense Boost', 1, 'Level 1: +5 Defense \n Level 2: +10 Defense \n Level 3: +5% Defense and Bonus +10. \n Level 4: +5% Defense, Bonus +20 and +3 to All Elemental Resistances \n Level 5: +8% Defense, Bonus +20 and +3 to All Elemental Resistances \n Level 6: +8% Defense, Bonus +35 and +5 to All Elemental Resistances \n Level 7: +10% Defense, Bonus +35 and +5 to All Elemental Resistances', 65, 'High Metal Braces'),
(66, 'Capacity Boost', 1, 'Level 1: Loading Capacity +1. (Increases maximum shield charge duration of Charge Blades by 30 seconds (up to 3 min))', 66, 'High Metal Coil'),
(67, 'Heavy Artillery', 1, 'Level 1: Firepower +50% (value changed in patch 6.02) \n Level 2: Firepower +100% (value changed in patch 6.02)', 67, 'High Metal Greaves'),
(68, 'Evade Window', 1, 'Level 1: Very slightly increases invulnerability window. \n Level 2: Slightly increases invulnerability window. \n Level 3: Increases invulnerability window \n Level 4: Greatly increases invulnerability window. \n Level 5: Massively increases invulnerability window.', 68, 'King Beetle Vertex'),
(69, "Quick Sheath", 1, ' Level 1: Slightly increases sheathing speed. \n Level 2: Moderately increases sheathing speed. \n Level 3: Greatly increases sheathing speed.', 69, 'King Beetle Thorax'),
(70, 'Leap of Faith', 1, 'Level 1: Allows you to do a dive-evade when facing towards large monsters, and extends the dive-evade distance.', 70, 'King Beetle Brachia'),
(71, 'Honey Hunter', 1, 'Level 1: One extra honey per gather.', 71, 'King Beetle Elytra'),
(72, "Forager's Luck", 1, 'Level 1: Increases the likelihood of rare gathering points respawning.', 72, 'King Beetle Crura'),
(73, 'Detector', 1, 'Level 1: Marks rare sites on the wildlife map.', 78, 'Shamos Goggles'),
(74, 'Dungmaster', 1, 'Level 1: Makes slinger Dung Pods more effective at making monsters run away', 79, 'Hornetaur Helm'),
(75, 'Effluvial Expert', 1, 'Level 1: Nullifies damage from Effluvia and reduces damage from acids', 80, 'Hornetaur Mail'),
(76, 'Free Meal', 1, 'Level 1: Activates 25% of the time \n Level 2: Activates 50% of the time (Iceborne only) \n Level 3: Activates 75% of the time (Iceborne only)', 81, 'Hornetaur Vambraces'),
(77, 'Carving Pro', 1, 'Level 1: Prevents knockback while carving', 82, 'Hornetaur Coil'),
(78, 'Handicraft', 1, 'Level 1: Weapon Sharpness +10 \n Level 2: Weapon Sharpness +20 \n Level 3: Weapon Sharpness +30 \n Level 4: Weapon Sharpness +40 \n Level 5: Weapon Sharpness +50', 83, 'Hornetaur Greaves'),
(79, 'Fire Attack', 1, 'Level 1: +30 Fire Attack. \n Level 2: +60 Fire Attack. \n Level 3: +100 Fire Attack. \n Level 4: +5% Fire Attack and +100 Fire Attack. \n Level 5: +10% Fire Attack and +100 Fire Attack. \n Level 6: +20% Fire Attack and +100 Fire Attack.', 84, 'Anja Helm'),
(80, 'Marathon Runner', 1, 'Level 1: Reduces continuous stamina depletion by 15%. \n Level 2: Reduces continuous stamina depletion by 30%. \n Level 3: Reduces continuous stamina depletion by 50%.', 85, 'Anja Mail'),
(81, 'Special Ammo Boost', 1, 'Level 1: Increases the power of bowgun special ammo, Dragon Piercer,  and Thousand Dragons by 10%. \n Level 2: Increases the power of bowgun special ammo, Dragon Piercer, and Thousand Dragons by 20%.', 86, 'Anja Vambraces'),
(82, 'Fire Resistance', 1, 'Level 1: +6 Fire Resistance. \n Level 2: +12 Fire Resistance. \n Level 3: +20 Fire Resistance and +10 Defense.', 87, 'Anja Coil'),
(83, 'Artillery', 1, "Level 1: Increases power of each attack by 10% and reduces Wyvern's Fire cooldown by 15% \n Level 2: Increases power of each attack by 20% and reduces Wyvern's Fire cooldown by 30% \n Level 3: Increases power of each attack by 30% and reduces Wyvern's Fire cooldown by 50% \n Level 4: Increases power of each attack by 40% and reduces Wyvern's Fire cooldown by 60% (Iceborne only) \n Level 5: Increases power of each attack by 50% and reduces Wyvern's Fire cooldown by 70% (Iceborne only)", 88, 'Anja Greaves'),
(84, 'Health Boost', 1, 'Level 1: Health +15 \n Level 2: Health +30 \n Level 3: Health +50', 89, 'Rathian Helm'),
(85, 'Botanist', 1, 'Level 1: One extra consumable herb item per gather. \n Level 2: One extra consumable herb, fruit, nut, or seed item per gather. \n Level 3: One extra consumable herb, fruit, nut, seed, or insect item per gather. \n Level 4: One extra consumable herb, fruit, nut, seed, insect, or mushroom item per gather.', 90, 'Rathian Mail'),
(86, 'Poison Attack', 1, 'Level 1: Poison buildup +5% Bonus: +10 \n Level 2: Poison buildup +10% Bonus: +10 \n Level 3: Poison buildup +20% Bonus: +10 \n Level 4: Poison buildup +30% Bonus: +10 (Iceborne only)', 91, 'Rathian Vambraces'),
(87, 'Poison Resistance', 1, ' Level 1: Reduces the duration of poison by 30%. \n Level 2: Reduces the duration of poison by 60%. \n Level 3: Prevents poison.', 92, 'Rathian Coil'),
(88, 'Recovery Up', 1, 'Level 1: Health Restoring effects are 10% more effective. \n Level 2: Health Restoring effects are 20% more effective. \n Level 3: Health Restoring effects are 30% more effective.', 93, 'Rathian Greaves'),
(89, 'Blindsider', 1, 'Level 1: Increases the effective range of flash attacks (changed in patch 6.02)', 94, 'Tzitzi Headgear'),
(90, 'Constitution', 1, 'Level 1: Reduces fixed stamina depletion by 10%. \n Level 2: Reduces fixed stamina depletion by 20%. \n Level 3: Reduces fixed stamina depletion by 30%. \n Level 4: Reduces fixed stamina depletion by 40%. \n Level 5: Reduces fixed stamina depletion by 50%.', 95, 'Tzitzi Mail'),
(91, 'Stun Resistance', 1, 'Level 1: Reduces Stun duration by 60% (value changed in patch 6.02) \n Level 2: Reduces Stun duration by 90% (value changed in patch 6.02) \n Level 3: Prevents Stun', 96, 'Tzitzi Vambracesl'),
(92, 'Wide-Range', 1, 'Level 1: Items affect nearby allies with 33% of their efficacy. \n Level 2: Items affect nearby allies in a wider radius with 33% of their efficacy. \n Level 3: Items affect nearby allies in a wider radius with 66% of their efficacy. \n Level 4: Items affect nearby allies in a much wider radius with 66% of their efficacy. \n Level 5: Items affect nearby allies in a much wider radius with full efficacy', 97, 'Tzitzi Coil'),
(93, 'Sleep Resistance', 1, 'Level 1: Reduces the duration of Sleep by 30% \n Level 2: Reduces the duration of Sleep by 60% \n Level 3: Prevents Sleep', 98, 'Tzitzi Greaves'),
(94, 'Stamina Surge', 1, 'Level 1: Stamina recovery speed +10% \n Level 2: Stamina recovery speed +20% \n Level 3: Stamina recovery speed +30%', 99, 'Lumu Hat'),
(95, 'Master Mounter', 1, 'Level 1: Makes it easier to mount and topple Monsters', 100, 'Lumu Mail'),
(96, 'Artillery', 1, "Level 1: Increases power of each attack by 10% and reduces Wyvern's Fire cooldown by 15% \n Level 2: Increases power of each attack by 20% and reduces Wyvern's Fire cooldown by 30% \n Level 3: Increases power of each attack by 30% and reduces Wyvern's Fire cooldown by 50% \n Level 4: Increases power of each attack by 40% and reduces Wyvern's Fire cooldown by 60%  (Iceborne only) \n Level 5: Increases power of each attack by 50% and reduces Wyvern's Fire cooldown by 70% (Iceborne only)", 101, 'Lumu Vambraces'),
(97, 'Divine Blessing', 1, 'Level 1: While active, reduces damage taken by 15% \n Level 2: While active, reduces damage taken by 30% \n Level 3: While active, reduces damage taken by 50% \n Level 4: While active, reduces damage taken by 60% (requires Divine Blessing Secret) (Iceborne only) \n Level 5: While active, reduces damage taken by 60%. Skill becomes easier to activate as well (Iceborne only)',102, 'Lumu Coil'),
(98, 'Windproof', 1, 'Level 1: Slightly reduces the effects of minor wind pressure. \n Level 2: Reduces the effects of minor wind pressure. \n Level 3: Negates minor wind pressure. \n Level 4: Negates minor wind pressure and reduces the effects of major wind pressure. \n Level 5: Negates minor and major wind pressure.', 103, 'Lumu Greaves'),
(99, 'Horn Maestro', 1, 'Level 1: Extends melody effect duration and increases health recovery \n Level 2: Greatly increases the effect duration of hunting horn melodies (Iceborne only)', 104, 'Girros Mask'),
(100, 'Paralysis Resistance', 1, 'Level 1: Reduces the duration of paralysis by 30%. \n Level 2: Reduces the duration of paralysis by 60%. \n Level 3: Prevents paralysis.', 105, 'Girros Mail'),
(101, 'Palico Rally', 1, 'Level 1: Increases Palico attack power and defense by 5% \n Level 2: Increases Palico attack power and defense by 10% \n Level 3: Increases Palico attack power and defense by 15% \n Level 4: Increases Palico attack power and defense by 20% \n Level 5: Increases Palico attack power and defense by 25%', 106, 'Girros Vambraces'),
(102, 'Effluvial Expert', 1, 'Level 1: Nullifies damage from Effluvia and reduces damage from acids', 107, 'Girros Coil'),
(103, 'Paralysis Attack', 1, 'Level 1: Paralysis buildup +5% Bonus: +10 \n Level 2: Paralysis buildup +10% Bonus: +10 \n Level 3: Paralysis buildup +20% Bonus: +10 \n Level 4: Paralysis buildup +30% Bonus: +10 (Iceborne only)', 108, 'Girros Greaves'),
(104, 'Slugger', 1, 'Level 1: Stun power +20% \n Level 2: Stun power +30% \n Level 3: Stun power +40% \n Level 4: Stun power +50%  (Iceborne only) \n Level 5: Stun power +60%  (Iceborne only)', 109, 'Baan Helm'),
(104, 'Sleep Resistance', 1, 'Level 1: Reduces the duration of Sleep by 30% \n Level 2: Reduces the duration of Sleep by 60% \n Level 3: Prevents Sleep', 110, 'Baan Mail'),
(104, 'Sleep Attack', 1, 'Level 1: Sleep buildup +5% Bonus: +10 \n Level 2: Sleep buildup +10% Bonus: +10 \n Level 3: Sleep buildup +20% Bonus: +10', 111, 'Baan Vambraces'),
(104, 'Guard', 1, 'Level 1: Slightly decreases the impact of attacks. \n Level 2: Slightly decreases the impact of attacks and reduces stamina depletion by 15%. \n Level 3: Greatly decreases the impact of attacks and reduces stamina depletion by 15%. \n Level 4: Greatly decreases the impact of attacks and reduces stamina depletion by 30%. \n Level 5: Massively decreases the impact of attacks and reduces stamina depletion by 50%.', 112, 'Baan Coil'),
(104, 'Bleeding Resistance', 1, 'Level 1: Reduces damage while Bleeding \n Level 2: Greatly reduces damage while Bleeding \n Level 3: Prevents Bleeding', 113, 'Baan Greaves'),
(104, 'Thunder Attack', 1, 'Level 1: +30 Thunder Attack. \n Level 2: +60 Thunder Attack. \n Level 3: +100 Thunder Attack. \n Level 4: +5% Thunder Attack and +100 Thunder Attack. \n Level 5: +10% Thunder Attack and +100 Thunder Attack. \n Level 6: +20% Thunder Attack and +100 Thunder Attack.', 114, 'Ingot Helm');



